/* ==== FILE: src/work-spine/scanned-evidence/scanned-evidence-static-batch.ts ==== */

// #region Imports
import { SCANNED_EVIDENCE_SAFETY_STATUS } from './scanned-evidence-types';
import type { ScannedEvidenceBatch, ScannedEvidenceCandidate } from './scanned-evidence-types';
// #endregion

// #region Constants
/** Stable identifier for the first static scans folder snapshot batch. */
export const STATIC_SCANNED_EVIDENCE_BATCH_ID = 'scans-folder-static-batch-v1';

/** Static source folder label for the first scanned evidence batch. */
export const STATIC_SCANNED_EVIDENCE_SOURCE_FOLDER_LABEL = 'scans-folder-default-inbox';

const DEFAULT_SOURCE_TRACE =
  'Static snapshot entry prepared from a scan label only; no document contents are represented.';

const COMMON_MISSING_FIELDS = [
  'client_or_matter',
  'document_date',
  'amount',
  'vat',
  'deadline',
  'counterparty',
  'supplier',
  'authority',
  'employee',
  'external_status',
] as const;
// #endregion

// #region Static Data
const STATIC_SCANNED_EVIDENCE_CANDIDATES: readonly ScannedEvidenceCandidate[] = [
  {
    evidenceId: 'scanned-evidence-001',
    batchId: STATIC_SCANNED_EVIDENCE_BATCH_ID,
    sourceFileName: 'supplier_invoice_bezeq_2026_01_scan.jpg',
    sourceFolderLabel: STATIC_SCANNED_EVIDENCE_SOURCE_FOLDER_LABEL,
    documentKind: 'supplier_invoice',
    professionalDomain: 'accounting',
    clientOrMatterGuess: null,
    counterparty: null,
    supplier: 'Bezeq',
    authority: null,
    employee: null,
    documentDate: null,
    periodDescription: '01/2026',
    amountIfKnown: null,
    vatIfRelevant: null,
    deadlineIfRelevant: null,
    externalSystemStatusIfKnown: null,
    duplicateRisk: 'possible',
    suggestedActionPreview: 'preview_only_vat_mapping',
    missingFields: COMMON_MISSING_FIELDS.filter((fieldName) => fieldName !== 'supplier'),
    sourceTrace: DEFAULT_SOURCE_TRACE,
    confidence: 'low',
    safetyStatus: SCANNED_EVIDENCE_SAFETY_STATUS,
  },
  {
    evidenceId: 'scanned-evidence-002',
    batchId: STATIC_SCANNED_EVIDENCE_BATCH_ID,
    sourceFileName: 'demand_letter_general_scan.jpg',
    sourceFolderLabel: STATIC_SCANNED_EVIDENCE_SOURCE_FOLDER_LABEL,
    documentKind: 'demand_letter',
    professionalDomain: 'legal',
    clientOrMatterGuess: null,
    counterparty: null,
    supplier: null,
    authority: null,
    employee: null,
    documentDate: null,
    periodDescription: null,
    amountIfKnown: null,
    vatIfRelevant: null,
    deadlineIfRelevant: null,
    externalSystemStatusIfKnown: null,
    duplicateRisk: 'unknown',
    suggestedActionPreview: 'preview_only_review',
    missingFields: [...COMMON_MISSING_FIELDS, 'period'],
    sourceTrace: DEFAULT_SOURCE_TRACE,
    confidence: 'low',
    safetyStatus: SCANNED_EVIDENCE_SAFETY_STATUS,
  },
  {
    evidenceId: 'scanned-evidence-003',
    batchId: STATIC_SCANNED_EVIDENCE_BATCH_ID,
    sourceFileName: 'fine_or_penalty_municipal_scan.jpg',
    sourceFolderLabel: STATIC_SCANNED_EVIDENCE_SOURCE_FOLDER_LABEL,
    documentKind: 'fine_or_penalty',
    professionalDomain: 'support',
    clientOrMatterGuess: null,
    counterparty: null,
    supplier: null,
    authority: 'municipal authority',
    employee: null,
    documentDate: null,
    periodDescription: null,
    amountIfKnown: null,
    vatIfRelevant: null,
    deadlineIfRelevant: null,
    externalSystemStatusIfKnown: null,
    duplicateRisk: 'unknown',
    suggestedActionPreview: 'preview_only_deadline_check',
    missingFields: [...COMMON_MISSING_FIELDS.filter((fieldName) => fieldName !== 'authority'), 'period'],
    sourceTrace: DEFAULT_SOURCE_TRACE,
    confidence: 'low',
    safetyStatus: SCANNED_EVIDENCE_SAFETY_STATUS,
  },
  {
    evidenceId: 'scanned-evidence-004',
    batchId: STATIC_SCANNED_EVIDENCE_BATCH_ID,
    sourceFileName: 'debt_notice_general_scan.jpg',
    sourceFolderLabel: STATIC_SCANNED_EVIDENCE_SOURCE_FOLDER_LABEL,
    documentKind: 'debt_notice',
    professionalDomain: 'accounting',
    clientOrMatterGuess: null,
    counterparty: null,
    supplier: null,
    authority: null,
    employee: null,
    documentDate: null,
    periodDescription: null,
    amountIfKnown: null,
    vatIfRelevant: null,
    deadlineIfRelevant: null,
    externalSystemStatusIfKnown: null,
    duplicateRisk: 'unknown',
    suggestedActionPreview: 'preview_only_review',
    missingFields: [...COMMON_MISSING_FIELDS, 'period'],
    sourceTrace: DEFAULT_SOURCE_TRACE,
    confidence: 'low',
    safetyStatus: SCANNED_EVIDENCE_SAFETY_STATUS,
  },
  {
    evidenceId: 'scanned-evidence-005',
    batchId: STATIC_SCANNED_EVIDENCE_BATCH_ID,
    sourceFileName: 'payroll_document_monthly_scan.jpg',
    sourceFolderLabel: STATIC_SCANNED_EVIDENCE_SOURCE_FOLDER_LABEL,
    documentKind: 'payroll_document',
    professionalDomain: 'employee',
    clientOrMatterGuess: null,
    counterparty: null,
    supplier: null,
    authority: null,
    employee: null,
    documentDate: null,
    periodDescription: null,
    amountIfKnown: null,
    vatIfRelevant: null,
    deadlineIfRelevant: null,
    externalSystemStatusIfKnown: null,
    duplicateRisk: 'possible',
    suggestedActionPreview: 'preview_only_payroll_review',
    missingFields: [...COMMON_MISSING_FIELDS, 'period'],
    sourceTrace: DEFAULT_SOURCE_TRACE,
    confidence: 'low',
    safetyStatus: SCANNED_EVIDENCE_SAFETY_STATUS,
  },
  {
    evidenceId: 'scanned-evidence-006',
    batchId: STATIC_SCANNED_EVIDENCE_BATCH_ID,
    sourceFileName: 'legal_letter_general_scan.jpg',
    sourceFolderLabel: STATIC_SCANNED_EVIDENCE_SOURCE_FOLDER_LABEL,
    documentKind: 'legal_letter',
    professionalDomain: 'legal',
    clientOrMatterGuess: null,
    counterparty: null,
    supplier: null,
    authority: null,
    employee: null,
    documentDate: null,
    periodDescription: null,
    amountIfKnown: null,
    vatIfRelevant: null,
    deadlineIfRelevant: null,
    externalSystemStatusIfKnown: null,
    duplicateRisk: 'unknown',
    suggestedActionPreview: 'preview_only_legal_review',
    missingFields: [...COMMON_MISSING_FIELDS, 'period'],
    sourceTrace: DEFAULT_SOURCE_TRACE,
    confidence: 'low',
    safetyStatus: SCANNED_EVIDENCE_SAFETY_STATUS,
  },
  {
    evidenceId: 'scanned-evidence-007',
    batchId: STATIC_SCANNED_EVIDENCE_BATCH_ID,
    sourceFileName: 'tax_report_period_unclear_scan.jpg',
    sourceFolderLabel: STATIC_SCANNED_EVIDENCE_SOURCE_FOLDER_LABEL,
    documentKind: 'tax_report',
    professionalDomain: 'reports',
    clientOrMatterGuess: null,
    counterparty: null,
    supplier: null,
    authority: 'tax authority',
    employee: null,
    documentDate: null,
    periodDescription: null,
    amountIfKnown: null,
    vatIfRelevant: null,
    deadlineIfRelevant: null,
    externalSystemStatusIfKnown: null,
    duplicateRisk: 'unknown',
    suggestedActionPreview: 'preview_only_classification',
    missingFields: [...COMMON_MISSING_FIELDS.filter((fieldName) => fieldName !== 'authority'), 'period'],
    sourceTrace: DEFAULT_SOURCE_TRACE,
    confidence: 'low',
    safetyStatus: SCANNED_EVIDENCE_SAFETY_STATUS,
  },
  {
    evidenceId: 'scanned-evidence-008',
    batchId: STATIC_SCANNED_EVIDENCE_BATCH_ID,
    sourceFileName: 'bank_or_credit_document_scan.jpg',
    sourceFolderLabel: STATIC_SCANNED_EVIDENCE_SOURCE_FOLDER_LABEL,
    documentKind: 'bank_or_credit_document',
    professionalDomain: 'accounting',
    clientOrMatterGuess: null,
    counterparty: null,
    supplier: null,
    authority: null,
    employee: null,
    documentDate: null,
    periodDescription: null,
    amountIfKnown: null,
    vatIfRelevant: null,
    deadlineIfRelevant: null,
    externalSystemStatusIfKnown: null,
    duplicateRisk: 'unknown',
    suggestedActionPreview: 'preview_only_review',
    missingFields: [...COMMON_MISSING_FIELDS, 'period'],
    sourceTrace: DEFAULT_SOURCE_TRACE,
    confidence: 'low',
    safetyStatus: SCANNED_EVIDENCE_SAFETY_STATUS,
  },
  {
    evidenceId: 'scanned-evidence-009',
    batchId: STATIC_SCANNED_EVIDENCE_BATCH_ID,
    sourceFileName: 'unknown_scan_awaiting_review.jpg',
    sourceFolderLabel: STATIC_SCANNED_EVIDENCE_SOURCE_FOLDER_LABEL,
    documentKind: 'unknown',
    professionalDomain: 'unknown',
    clientOrMatterGuess: null,
    counterparty: null,
    supplier: null,
    authority: null,
    employee: null,
    documentDate: null,
    periodDescription: null,
    amountIfKnown: null,
    vatIfRelevant: null,
    deadlineIfRelevant: null,
    externalSystemStatusIfKnown: null,
    duplicateRisk: 'unknown',
    suggestedActionPreview: 'preview_only_unknown_triage',
    missingFields: [...COMMON_MISSING_FIELDS, 'period', 'classification'],
    sourceTrace: DEFAULT_SOURCE_TRACE,
    confidence: 'low',
    safetyStatus: SCANNED_EVIDENCE_SAFETY_STATUS,
  },
];

/** First static scanned evidence batch for preview-only intake planning. */
export const STATIC_SCANNED_EVIDENCE_BATCH: ScannedEvidenceBatch = {
  batchId: STATIC_SCANNED_EVIDENCE_BATCH_ID,
  batchLabel: 'Static scans folder evidence candidates v1',
  sourceFolderLabel: STATIC_SCANNED_EVIDENCE_SOURCE_FOLDER_LABEL,
  sourceChannel: 'scans_folder_static_snapshot',
  createdFrom: 'static_manual_seed',
  candidates: STATIC_SCANNED_EVIDENCE_CANDIDATES,
};

/** Static scanned evidence batches available for preview-only review. */
export const STATIC_SCANNED_EVIDENCE_BATCHES: readonly ScannedEvidenceBatch[] = [
  STATIC_SCANNED_EVIDENCE_BATCH,
];
// #endregion
