/* ============================================
   FILE: processDefinitionsDomains.ts
   PURPOSE: הגדרות תהליכי עובדים, חישובים מיוחדים, דוחות כספיים
   DEPENDENCIES: ./processRegistry
   EXPORTS: DOMAIN_PROCESS_DEFINITIONS
   ============================================ */
import type { ProcessDefinition } from './processRegistry';

// #region Domain Definitions

/** תהליכי דומיינים מקצועיים */
export const DOMAIN_PROCESS_DEFINITIONS: ProcessDefinition[] = [

  // ═══════════════════════════════════════════
  // עובדים
  // ═══════════════════════════════════════════
  {
    id: 'attendance',
    title: 'ניהול נוכחות',
    emoji: '⏰',
    domain: 'employees',
    parentDomains: [],
    subProcesses: [],
    entities: [],
    queues: [],
    triggers: [{ type: 'manual' }],
    outputs: ['monthly_attendance_report', 'exceptions_report'],
    relatedProcesses: ['payroll_processing', 'worklaw'],
    status: 'active',
    route: '/flow/attendance',
    isVisibleInSidebar: true,
    isVisibleInDashboard: false,
    brainNodeId: 'attendance',
    category: 'workforce',
    flowchartFile: 'flowchart-attendance.html',
    brainKeywords: ['נוכחות', 'שעון', 'שעות', 'משמרות', 'שעות נוספות', 'attendance'],
    requiredInputs: ['employee_id', 'month', 'raw_attendance_report'],
    optionalInputs: ['sick_leave_docs', 'vacation_approvals'],
    agents: ['intake_agent', 'validation_agent', 'analysis_agent', 'document_agent', 'review_agent'],
    processStates: ['draft', 'collecting_data', 'validating', 'under_analysis', 'generating_output', 'under_review', 'completed'],
    screens: ['dashboard', 'ceo-office'],
  },
  {
    id: 'payroll_processing',
    title: 'עיבוד שכר',
    emoji: '💰',
    domain: 'employees',
    parentDomains: ['accounting'],
    subProcesses: [],
    entities: [],
    queues: [],
    triggers: [{ type: 'schedule' }],
    outputs: ['payslips', 'payroll_summary', 'institutional_files'],
    relatedProcesses: ['attendance', 'institutional_reports'],
    status: 'active',
    route: '/flow/payroll-processing',
    isVisibleInSidebar: true,
    isVisibleInDashboard: false,
    brainNodeId: 'payroll',
    category: 'workforce',
    flowchartFile: 'flowchart-payroll-processing.html',
    brainKeywords: ['שכר', 'משכורת', 'תלוש', 'payroll'],
    requiredInputs: ['attendance_report', 'employee_details', 'salary_terms'],
    agents: ['intake_agent', 'validation_agent', 'analysis_agent', 'document_agent', 'review_agent', 'submission_agent'],
    processStates: ['draft', 'collecting_data', 'under_analysis', 'generating_output', 'under_review', 'ready_for_submission', 'completed'],
    screens: ['dashboard', 'ceo-office'],
  },
  {
    id: 'worklaw',
    title: 'דיני עבודה',
    emoji: '⚖️',
    domain: 'employees',
    parentDomains: [],
    subProcesses: [],
    entities: [],
    queues: [],
    triggers: [{ type: 'manual' }],
    outputs: ['legal_opinion', 'action_letter'],
    relatedProcesses: ['attendance'],
    status: 'active',
    route: '/flow/worklaw',
    isVisibleInSidebar: true,
    isVisibleInDashboard: false,
    brainNodeId: 'worklaw',
    category: 'regulation',
    flowchartFile: 'flowchart-worklaw.html',
    brainKeywords: ['דיני עבודה', 'פיטורין', 'פיצויים', 'שימוע', 'worklaw'],
    requiredInputs: ['case_type', 'employee_details'],
    agents: ['intake_agent', 'validation_agent', 'decision_support_agent', 'document_agent'],
    screens: ['dashboard'],
  },
  {
    id: 'expert_opinion',
    title: 'חוות דעת מומחה',
    emoji: '📝',
    domain: 'employees',
    parentDomains: [],
    subProcesses: [],
    entities: [],
    queues: [],
    triggers: [{ type: 'manual' }],
    outputs: ['expert_opinion_document', 'financial_analysis'],
    relatedProcesses: ['guardian_pro'],
    status: 'active',
    route: '/flow/expert-opinion',
    isVisibleInSidebar: true,
    isVisibleInDashboard: false,
    brainNodeId: 'expert_opinion',
    category: 'expert_witness',
    flowchartFile: 'flowchart-expert-opinion.html',
    brainKeywords: ['חוות דעת', 'מומחה', 'הערכה כלכלית', 'expert opinion', 'בית משפט'],
    requiredInputs: ['case_details', 'court_documents', 'financial_data'],
    agents: ['intake_agent', 'validation_agent', 'analysis_agent', 'decision_support_agent', 'document_agent', 'review_agent'],
    screens: ['dashboard', 'ceo-office'],
  },

  // ═══════════════════════════════════════════
  // חישובים מיוחדים
  // ═══════════════════════════════════════════
  {
    id: 'capital_gains',
    title: 'רווח הון ממקרקעין בחו"ל',
    emoji: '💰',
    domain: 'special_claims',
    parentDomains: ['financial'],
    subProcesses: [],
    entities: [],
    queues: [],
    triggers: [{ type: 'manual' }],
    outputs: ['capital_gains_calculation', 'form_1399', 'bank_letter', 'submission_package'],
    relatedProcesses: ['declaration_of_capital'],
    status: 'active',
    route: '/flow/capital-gains',
    isVisibleInSidebar: true,
    isVisibleInDashboard: false,
    brainNodeId: 'capital_gains',
    category: 'tax',
    flowchartFile: 'flowchart-capital-gains.html',
    brainKeywords: ['רווח הון', 'מכירת נכס', 'מקרקעין', 'capital gains', 'טופס 1399', 'סעיף 91'],
    requiredInputs: ['property_purchase_docs', 'property_sale_docs', 'taxpayer_details', 'exchange_rates'],
    optionalInputs: ['depreciation_report', 'improvement_receipts'],
    agents: ['intake_agent', 'validation_agent', 'analysis_agent', 'decision_support_agent', 'document_agent', 'review_agent', 'submission_agent'],
    screens: ['dashboard', 'ceo-office', 'case-view'],
  },
  {
    id: 'guardian_pro',
    title: 'אפוטרופוס',
    emoji: '🏛️',
    domain: 'special_claims',
    parentDomains: [],
    subProcesses: [],
    entities: [],
    queues: [],
    triggers: [{ type: 'manual' }],
    outputs: ['annual_guardian_report', 'financial_summary'],
    relatedProcesses: ['expert_opinion', 'insolvency'],
    status: 'active',
    route: '/flow/guardian-pro',
    isVisibleInSidebar: true,
    isVisibleInDashboard: false,
    brainNodeId: 'guardian',
    category: 'guardianship',
    flowchartFile: 'flowchart-guardian-pro.html',
    brainKeywords: ['אפוטרופוס', 'חסוי', 'דוח שנתי', 'guardian', 'אפוטרופסות'],
    requiredInputs: ['ward_details', 'financial_records', 'court_orders'],
    agents: ['intake_agent', 'validation_agent', 'analysis_agent', 'document_agent', 'review_agent', 'submission_agent'],
    screens: ['dashboard', 'ceo-office', 'case-view'],
  },
  {
    id: 'insolvency',
    title: 'חדלות פירעון',
    emoji: '📉',
    domain: 'special_claims',
    parentDomains: [],
    subProcesses: [],
    entities: [],
    queues: [],
    triggers: [{ type: 'manual' }],
    outputs: ['monthly_guardian_report', 'financial_status'],
    relatedProcesses: ['guardian_pro'],
    status: 'active',
    route: '/flow/insolvency',
    isVisibleInSidebar: true,
    isVisibleInDashboard: false,
    brainNodeId: 'insolvency',
    category: 'bankruptcy',
    flowchartFile: 'flowchart-insolvency.html',
    brainKeywords: ['חדלות פירעון', 'פשט רגל', 'הסדר נושים', 'insolvency'],
    requiredInputs: ['debtor_details', 'creditor_list', 'financial_statements'],
    agents: ['intake_agent', 'validation_agent', 'analysis_agent', 'document_agent', 'review_agent', 'submission_agent'],
    screens: ['dashboard', 'ceo-office'],
  },

  // ═══════════════════════════════════════════
  // דוחות כספיים
  // ═══════════════════════════════════════════
  {
    id: 'declaration_of_capital',
    title: 'הצהרת הון',
    emoji: '📜',
    domain: 'financial',
    parentDomains: ['accounting'],
    subProcesses: [],
    entities: [],
    queues: [],
    triggers: [{ type: 'manual' }],
    outputs: ['declaration_report', 'tax_forms', 'submission_package'],
    relatedProcesses: ['capital_gains'],
    status: 'active',
    route: '/flow/declaration-of-capital',
    isVisibleInSidebar: true,
    isVisibleInDashboard: false,
    brainNodeId: 'declaration_of_capital',
    category: 'tax_reporting',
    flowchartFile: 'flowchart-declaration-of-capital.html',
    brainKeywords: ['הצהרת הון', 'הון נקי', 'נכסים', 'התחייבויות', 'declaration of capital'],
    requiredInputs: ['taxpayer_details', 'assets', 'liabilities', 'supporting_documents'],
    agents: ['intake_agent', 'validation_agent', 'analysis_agent', 'document_agent', 'review_agent', 'submission_agent'],
    screens: ['dashboard', 'ceo-office'],
  },
  {
    id: 'institutional_reports',
    title: 'דוחות מוסדיים',
    emoji: '📋',
    domain: 'accounting',
    parentDomains: [],
    subProcesses: [],
    entities: [],
    queues: [],
    triggers: [{ type: 'schedule' }],
    outputs: ['institutional_report', 'submission_confirmation'],
    relatedProcesses: ['payroll_processing', 'capital_gains'],
    status: 'active',
    route: '/flow/institutional-reports',
    isVisibleInSidebar: true,
    isVisibleInDashboard: false,
    brainNodeId: 'institutional_reports',
    category: 'compliance',
    flowchartFile: 'flowchart-institutional-reports.html',
    brainKeywords: ['דוח מוסדי', 'מס הכנסה', 'ביטוח לאומי', 'מע"מ', 'דוח שנתי'],
    requiredInputs: ['report_period', 'financial_data', 'entity_details'],
    agents: ['intake_agent', 'validation_agent', 'analysis_agent', 'document_agent', 'review_agent', 'submission_agent'],
    screens: ['dashboard', 'ceo-office'],
  },

  // ═══════════════════════════════════════════
  // תקשורת לקוחות
  // ═══════════════════════════════════════════
  {
    id: 'client_messaging',
    title: 'הודעות ללקוחות',
    emoji: '💬',
    domain: 'clients',
    parentDomains: ['accounting'],
    subProcesses: [],
    entities: [],
    queues: [],
    triggers: [{ type: 'manual' }],
    outputs: ['personalized_message', 'message_log'],
    relatedProcesses: ['war_compensation', 'capital_gains'],
    status: 'active',
    route: '/messaging',
    isVisibleInSidebar: true,
    isVisibleInDashboard: true,
    brainNodeId: 'messaging',
    category: 'communication',
    brainKeywords: ['הודעה', 'וואטסאפ', 'whatsapp', 'ברכת חג', 'תזכורת', 'עדכון', 'לקוח', 'שליחה'],
    requiredInputs: ['recipient_list', 'message_template_or_text'],
    optionalInputs: ['case_context', 'holiday_type'],
    agents: [],
    processStates: ['composing', 'ready', 'approved', 'sent', 'failed'],
    screens: ['dashboard', 'ceo-office', 'messaging'],
  },
];
// #endregion
