/* ====
   FILE: output-preview-seed.ts
   PURPOSE: Static Stage 10 professional output preview registry and mocks.
   DEPENDENCIES: Output preview contracts
   EXPORTS: Static output preview registry and preview mocks
   ==== */

// #region Imports
import type {
  OutputPreviewRegistryEntry,
  ProfessionalOutputPreview,
} from './output-preview-types';
import {
  OUTPUT_GENERATION_BLOCKED_REASON,
  OUTPUT_PREVIEW_STATUSES,
} from './output-preview-types';
// #endregion

// #region Registry
/** Static Stage 10 output type registry. */
export const OUTPUT_PREVIEW_TYPE_REGISTRY: readonly OutputPreviewRegistryEntry[] = [
  {
    outputType: 'letter',
    displayName: 'letter',
    allowedStatuses: OUTPUT_PREVIEW_STATUSES,
    generationBlocked: true,
    exportBlocked: true,
    staticPreviewOnly: true,
  },
  {
    outputType: 'task_summary',
    displayName: 'task summary',
    allowedStatuses: OUTPUT_PREVIEW_STATUSES,
    generationBlocked: true,
    exportBlocked: true,
    staticPreviewOnly: true,
  },
  {
    outputType: 'scan_intake_report',
    displayName: 'scan intake report',
    allowedStatuses: OUTPUT_PREVIEW_STATUSES,
    generationBlocked: true,
    exportBlocked: true,
    staticPreviewOnly: true,
  },
  {
    outputType: 'protocol_action_summary',
    displayName: 'protocol action summary',
    allowedStatuses: OUTPUT_PREVIEW_STATUSES,
    generationBlocked: true,
    exportBlocked: true,
    staticPreviewOnly: true,
  },
  {
    outputType: 'vat_review_memo',
    displayName: 'vat review memo',
    allowedStatuses: OUTPUT_PREVIEW_STATUSES,
    generationBlocked: true,
    exportBlocked: true,
    staticPreviewOnly: true,
  },
  {
    outputType: 'evidence_summary',
    displayName: 'evidence summary',
    allowedStatuses: OUTPUT_PREVIEW_STATUSES,
    generationBlocked: true,
    exportBlocked: true,
    staticPreviewOnly: true,
  },
  {
    outputType: 'professional_opinion_draft',
    displayName: 'professional opinion draft',
    allowedStatuses: OUTPUT_PREVIEW_STATUSES,
    generationBlocked: true,
    exportBlocked: true,
    staticPreviewOnly: true,
  },
];
// #endregion

// #region Static Previews
/** Static professional output previews with provenance only and no generated content. */
export const STATIC_OUTPUT_PREVIEWS: readonly ProfessionalOutputPreview[] = [
  {
    outputPreviewId: 'output-preview-letter-drive-vat',
    outputType: 'letter',
    outputStatus: 'preview_draft',
    sourceIntakeId: 'src-drive-202',
    sourceApprovalId: 'approval-stage7a-drive-approved-preview',
    sourceOperationalPreviewId: 'operational-preview-bundle-drive-vat',
    policyActionRef: 'generate_client_letter',
    professionalPurpose: 'Preview a client letter structure for later manual review.',
    intendedAudience: 'Client',
    languageDirection: 'ltr',
    riskLevel: 'high',
    requiredReviewer: 'Eldad',
    eldadMustReview: true,
    neverAutoGenerate: true,
    generationBlocked: true,
    generationBlockedReason: OUTPUT_GENERATION_BLOCKED_REASON,
  },
  {
    outputPreviewId: 'output-preview-task-summary-email',
    outputType: 'task_summary',
    outputStatus: 'structural_placeholder',
    sourceIntakeId: 'src-email-101',
    sourceApprovalId: 'approval-stage7a-email-pending',
    sourceOperationalPreviewId: 'operational-preview-bundle-email-pending',
    policyActionRef: 'classify_intake_candidate',
    professionalPurpose: 'Preview a task summary structure without creating a task.',
    intendedAudience: 'Internal review',
    languageDirection: 'ltr',
    riskLevel: 'low',
    requiredReviewer: 'Eldad',
    eldadMustReview: true,
    neverAutoGenerate: true,
    generationBlocked: true,
    generationBlockedReason: OUTPUT_GENERATION_BLOCKED_REASON,
  },
  {
    outputPreviewId: 'output-preview-scan-intake-report',
    outputType: 'scan_intake_report',
    outputStatus: 'preview_draft',
    sourceIntakeId: 'src-scan-303',
    sourceApprovalId: 'approval-stage7a-scan-rejected',
    sourceOperationalPreviewId: 'operational-preview-bundle-scan-rejected',
    policyActionRef: 'classify_intake_candidate',
    professionalPurpose: 'Preview scan intake metadata as an internal report shell.',
    intendedAudience: 'Internal review',
    languageDirection: 'ltr',
    riskLevel: 'medium',
    requiredReviewer: 'Eldad',
    eldadMustReview: true,
    neverAutoGenerate: true,
    generationBlocked: true,
    generationBlockedReason: OUTPUT_GENERATION_BLOCKED_REASON,
  },
  {
    outputPreviewId: 'output-preview-protocol-action-summary',
    outputType: 'protocol_action_summary',
    outputStatus: 'structural_placeholder',
    sourceIntakeId: 'protocol:protocol-stage6d1-client-call-002',
    sourceApprovalId: 'approval-stage7a-protocol-needs-evidence',
    sourceOperationalPreviewId: 'operational-preview-bundle-protocol-placeholder',
    policyActionRef: 'classify_intake_candidate',
    professionalPurpose: 'Preview protocol follow-up categories without extracting tasks.',
    intendedAudience: 'Internal review',
    languageDirection: 'ltr',
    riskLevel: 'medium',
    requiredReviewer: 'Eldad',
    eldadMustReview: true,
    neverAutoGenerate: true,
    generationBlocked: true,
    generationBlockedReason: OUTPUT_GENERATION_BLOCKED_REASON,
  },
  {
    outputPreviewId: 'output-preview-vat-review-memo-hebrew',
    outputType: 'vat_review_memo',
    outputStatus: 'preview_draft',
    sourceIntakeId: 'src-drive-202',
    sourceApprovalId: 'approval-stage7a-drive-approved-preview',
    sourceOperationalPreviewId: 'operational-preview-bundle-drive-vat',
    policyActionRef: 'approve_learning_candidate',
    professionalPurpose: 'תצוגת מבנה בלבד לסקירת מע״מ לפני בדיקת אלדד.',
    intendedAudience: 'אלדד',
    languageDirection: 'rtl',
    riskLevel: 'high',
    requiredReviewer: 'Eldad',
    eldadMustReview: true,
    neverAutoGenerate: true,
    generationBlocked: true,
    generationBlockedReason: OUTPUT_GENERATION_BLOCKED_REASON,
  },
  {
    outputPreviewId: 'output-preview-evidence-summary-scan',
    outputType: 'evidence_summary',
    outputStatus: 'structural_placeholder',
    sourceIntakeId: 'src-scan-303',
    sourceApprovalId: 'approval-stage7a-scan-rejected',
    sourceOperationalPreviewId: 'operational-preview-bundle-scan-rejected',
    policyActionRef: 'link_to_matter',
    professionalPurpose: 'Preview evidence summary structure without filing evidence.',
    intendedAudience: 'Internal review',
    languageDirection: 'ltr',
    riskLevel: 'medium',
    requiredReviewer: 'Eldad',
    eldadMustReview: true,
    neverAutoGenerate: true,
    generationBlocked: true,
    generationBlockedReason: OUTPUT_GENERATION_BLOCKED_REASON,
  },
  {
    outputPreviewId: 'output-preview-professional-opinion-draft',
    outputType: 'professional_opinion_draft',
    outputStatus: 'structural_placeholder',
    sourceIntakeId: 'src-drive-202',
    sourceApprovalId: 'approval-stage7a-drive-approved-preview',
    sourceOperationalPreviewId: 'operational-preview-bundle-drive-vat',
    policyActionRef: 'generate_client_letter',
    professionalPurpose: 'Preview a professional opinion structure for manual drafting only.',
    intendedAudience: 'Professional reviewer',
    languageDirection: 'ltr',
    riskLevel: 'critical',
    requiredReviewer: 'Eldad',
    eldadMustReview: true,
    neverAutoGenerate: true,
    generationBlocked: true,
    generationBlockedReason: OUTPUT_GENERATION_BLOCKED_REASON,
    manualOnly: true,
  },
] as const;
// #endregion
