/* ==== FILE: src/work-spine/visual-navigation/sidebar-separation-plan-seed.ts ==== */

// #region Imports
import type { SidebarSeparationPlanRow } from './sidebar-separation-plan-types';
// #endregion

// #region Constants
/** Hebrew label for the static Sidebar separation planning layer. */
export const SIDEBAR_SEPARATION_PLAN_LABEL = 'תוכנית הפרדת Sidebar סטטית';

/** Safety warning for the static Sidebar separation plan. */
export const SIDEBAR_SEPARATION_PLAN_WARNING =
  'תוכנית הפרדת Sidebar סטטית בלבד — לא משנה ניווט, לא מזיזה Routes, לא מוחקת תהליכים, ולא יוצרת אזורי עבודה.';

/** Static plan for separating professional process blueprints from operational navigation. */
export const SIDEBAR_SEPARATION_PLAN_ROWS: SidebarSeparationPlanRow[] = [
  {
    itemId: 'process-institutional-reports',
    hebrewLabel: 'דוחות מוסדיים',
    currentLocation: 'תפעול משרדי',
    currentRoute: '/flow/institutional-reports',
    proposedClassification: 'movesToProcessLibrary',
    reason: 'תהליך מקצועי תבניתי; עליו להופיע כספריית תהליכים ולא כאזור עבודה תפעולי.',
    targetLocation: 'Process Library / Professional Process Blueprints',
    implementationAllowed: false,
    requiresEldadApproval: true,
  },
  {
    itemId: 'process-penalty-cancellation',
    hebrewLabel: 'ביטול קנסות',
    currentLocation: 'תפעול משרדי',
    currentRoute: '/flow/penalty-cancellation',
    proposedClassification: 'movesToProcessLibrary',
    reason: 'תהליך מקצועי תבניתי; עליו להופיע כספריית תהליכים ולא כאזור עבודה תפעולי.',
    targetLocation: 'Process Library / Professional Process Blueprints',
    implementationAllowed: false,
    requiresEldadApproval: true,
  },
  {
    itemId: 'process-declaration-of-capital',
    hebrewLabel: 'הצהרת הון',
    currentLocation: 'תפעול משרדי',
    currentRoute: '/flow/declaration-of-capital',
    proposedClassification: 'movesToProcessLibrary',
    reason: 'תהליך מקצועי תבניתי; עליו להופיע כספריית תהליכים ולא כאזור עבודה תפעולי.',
    targetLocation: 'Process Library / Professional Process Blueprints',
    implementationAllowed: false,
    requiresEldadApproval: true,
  },
  {
    itemId: 'process-vat-report',
    hebrewLabel: 'דו"ח מע"מ',
    currentLocation: 'תפעול משרדי',
    currentRoute: '/coming-soon',
    proposedClassification: 'movesToProcessLibrary',
    reason: 'תהליך מקצועי תבניתי; עליו להופיע כספריית תהליכים ולא כאזור עבודה תפעולי.',
    targetLocation: 'Process Library / Professional Process Blueprints',
    implementationAllowed: false,
    requiresEldadApproval: true,
  },
  {
    itemId: 'process-attendance',
    hebrewLabel: 'נוכחות עובדים',
    currentLocation: 'תפעול משרדי',
    currentRoute: '/flow/attendance',
    proposedClassification: 'movesToProcessLibrary',
    reason: 'תהליך מקצועי תבניתי; עליו להופיע כספריית תהליכים ולא כאזור עבודה תפעולי.',
    targetLocation: 'Process Library / Professional Process Blueprints',
    implementationAllowed: false,
    requiresEldadApproval: true,
  },
  {
    itemId: 'process-attendance-agents',
    hebrewLabel: 'סוכני נוכחות',
    currentLocation: 'תפעול משרדי',
    currentRoute: '/flow/attendance-agents',
    proposedClassification: 'movesToProcessLibrary',
    reason: 'תהליך מקצועי תבניתי; עליו להופיע כספריית תהליכים ולא כאזור עבודה תפעולי.',
    targetLocation: 'Process Library / Professional Process Blueprints',
    implementationAllowed: false,
    requiresEldadApproval: true,
  },
  {
    itemId: 'process-payroll-processing',
    hebrewLabel: 'עיבוד שכר',
    currentLocation: 'תפעול משרדי',
    currentRoute: '/flow/payroll-processing',
    proposedClassification: 'movesToProcessLibrary',
    reason: 'תהליך מקצועי תבניתי; עליו להופיע כספריית תהליכים ולא כאזור עבודה תפעולי.',
    targetLocation: 'Process Library / Professional Process Blueprints',
    implementationAllowed: false,
    requiresEldadApproval: true,
  },
  {
    itemId: 'process-worklaw',
    hebrewLabel: 'דיני עבודה',
    currentLocation: 'תפעול משרדי',
    currentRoute: '/flow/worklaw',
    proposedClassification: 'movesToProcessLibrary',
    reason: 'תהליך מקצועי תבניתי; עליו להופיע כספריית תהליכים ולא כאזור עבודה תפעולי.',
    targetLocation: 'Process Library / Professional Process Blueprints',
    implementationAllowed: false,
    requiresEldadApproval: true,
  },
  {
    itemId: 'process-expert-opinion',
    hebrewLabel: 'חוות דעת מומחה',
    currentLocation: 'תפעול משרדי',
    currentRoute: '/flow/expert-opinion',
    proposedClassification: 'movesToProcessLibrary',
    reason: 'תהליך מקצועי תבניתי; עליו להופיע כספריית תהליכים ולא כאזור עבודה תפעולי.',
    targetLocation: 'Process Library / Professional Process Blueprints',
    implementationAllowed: false,
    requiresEldadApproval: true,
  },
  {
    itemId: 'process-capital-gains',
    hebrewLabel: 'רווח הון ממקרקעין בחו"ל',
    currentLocation: 'תפעול משרדי',
    currentRoute: '/flow/capital-gains',
    proposedClassification: 'movesToProcessLibrary',
    reason: 'תהליך מקצועי תבניתי; עליו להופיע כספריית תהליכים ולא כאזור עבודה תפעולי.',
    targetLocation: 'Process Library / Professional Process Blueprints',
    implementationAllowed: false,
    requiresEldadApproval: true,
  },
  {
    itemId: 'process-guardian',
    hebrewLabel: 'אפוטרופוס',
    currentLocation: 'תפעול משרדי',
    currentRoute: '/flow/guardian-pro',
    proposedClassification: 'movesToProcessLibrary',
    reason: 'תהליך מקצועי תבניתי; עליו להופיע כספריית תהליכים ולא כאזור עבודה תפעולי.',
    targetLocation: 'Process Library / Professional Process Blueprints',
    implementationAllowed: false,
    requiresEldadApproval: true,
  },
  {
    itemId: 'process-war-compensation',
    hebrewLabel: 'פיצויי מלחמה',
    currentLocation: 'תפעול משרדי',
    currentRoute: '/flow/war-compensation',
    proposedClassification: 'movesToProcessLibrary',
    reason: 'תהליך מקצועי תבניתי; עליו להופיע כספריית תהליכים ולא כאזור עבודה תפעולי.',
    targetLocation: 'Process Library / Professional Process Blueprints',
    implementationAllowed: false,
    requiresEldadApproval: true,
  },
  {
    itemId: 'process-insolvency',
    hebrewLabel: 'חדלות פירעון',
    currentLocation: 'תפעול משרדי',
    currentRoute: '/flow/insolvency',
    proposedClassification: 'movesToProcessLibrary',
    reason: 'תהליך מקצועי תבניתי; עליו להופיע כספריית תהליכים ולא כאזור עבודה תפעולי.',
    targetLocation: 'Process Library / Professional Process Blueprints',
    implementationAllowed: false,
    requiresEldadApproval: true,
  },
  {
    itemId: 'work-clients-index',
    hebrewLabel: 'לקוחות',
    currentLocation: 'לקוחות ותיקים',
    currentRoute: '/clients',
    proposedClassification: 'staysInSidebar',
    reason: 'אזור עבודה תפעולי קיים לניווט לקוחות; אינו תהליך מקצועי תבניתי.',
    targetLocation: 'Operational Sidebar / Clients and Cases',
    implementationAllowed: false,
    requiresEldadApproval: true,
  },
  {
    itemId: 'work-leads',
    hebrewLabel: 'לידים',
    currentLocation: 'לקוחות ותיקים',
    currentRoute: '/leads',
    proposedClassification: 'staysInSidebar',
    reason: 'אזור עבודה תפעולי קיים לניהול פניות; אינו תהליך מקצועי תבניתי.',
    targetLocation: 'Operational Sidebar / Clients and Cases',
    implementationAllowed: false,
    requiresEldadApproval: true,
  },
  {
    itemId: 'work-onboarding',
    hebrewLabel: 'קליטת לקוח חדש',
    currentLocation: 'לקוחות ותיקים',
    currentRoute: '/onboarding',
    proposedClassification: 'staysInSidebar',
    reason: 'אזור עבודה תפעולי קיים לקליטת לקוח; דורש הפרדה מתבניות תהליך.',
    targetLocation: 'Operational Sidebar / Clients and Cases',
    implementationAllowed: false,
    requiresEldadApproval: true,
  },
  {
    itemId: 'work-active-cases',
    hebrewLabel: 'תיקים פעילים',
    currentLocation: 'לקוחות ותיקים',
    currentRoute: '/case/:caseId',
    proposedClassification: 'staysInSidebar',
    reason: 'אזור עבודה תפעולי קיים לתיקים; אינו תהליך מקצועי תבניתי.',
    targetLocation: 'Operational Sidebar / Clients and Cases',
    implementationAllowed: false,
    requiresEldadApproval: true,
  },
  {
    itemId: 'work-helman-case',
    hebrewLabel: 'תיק הלמן',
    currentLocation: 'לקוחות ותיקים',
    currentRoute: '/case/helman',
    proposedClassification: 'staysInSidebar',
    reason: 'תיק/מרחב עבודה ספציפי; נשאר בצד התפעולי בכפוף לאישור אלדד.',
    targetLocation: 'Operational Sidebar / Clients and Cases',
    implementationAllowed: false,
    requiresEldadApproval: true,
  },
  {
    itemId: 'work-guardian-case',
    hebrewLabel: 'תיק אפוטרופוס',
    currentLocation: 'לקוחות ותיקים',
    currentRoute: '/case/guardian',
    proposedClassification: 'staysInSidebar',
    reason: 'תיק/מרחב עבודה ספציפי; נשאר בצד התפעולי בכפוף לאישור אלדד.',
    targetLocation: 'Operational Sidebar / Clients and Cases',
    implementationAllowed: false,
    requiresEldadApproval: true,
  },
  {
    itemId: 'work-tsila-case',
    hebrewLabel: 'עבודה אקדמית — צילה',
    currentLocation: 'לקוחות ותיקים',
    currentRoute: '/case/tsila-shvartz',
    proposedClassification: 'staysInSidebar',
    reason: 'מרחב עבודה קונקרטי; אינו תהליך מקצועי תבניתי.',
    targetLocation: 'Operational Sidebar / Clients and Cases',
    implementationAllowed: false,
    requiresEldadApproval: true,
  },
  {
    itemId: 'work-spine-board',
    hebrewLabel: 'Work Spine board',
    currentLocation: 'Work Spine',
    currentRoute: '/work-spine',
    proposedClassification: 'staysInSidebar',
    reason: 'משטח שליטה תפעולי פנימי; אינו שייך לספריית תהליכים מקצועיים.',
    targetLocation: 'Operational Sidebar / Work Spine',
    implementationAllowed: false,
    requiresEldadApproval: true,
  },
  {
    itemId: 'control-command-palette',
    hebrewLabel: 'Command Palette',
    currentLocation: 'Global command surface',
    currentRoute: null,
    proposedClassification: 'needsEldadDecision',
    reason: 'משטח פקודות חזותי גלובלי; נדרש אישור אלדד לפני שיוך לצד תפעולי או לצד בקרה.',
    targetLocation: 'Control Views / Quick Command Surface',
    implementationAllowed: false,
    requiresEldadApproval: true,
  },
  {
    itemId: 'process-brain-router',
    hebrewLabel: 'נתב המוח',
    currentLocation: 'Knowledge & AI',
    currentRoute: '/flow/brain-router',
    proposedClassification: 'needsEldadDecision',
    reason: 'תבנית ניווט/בקרה של המוח; אינה תיק תפעולי ואינה תהליך מקצועי רגיל.',
    targetLocation: 'Control Views / Brain Routing Blueprint',
    implementationAllowed: false,
    requiresEldadApproval: true,
  },
];
// #endregion
