/* ==== FILE: src/work-spine/knowledge-inventory/brain-knowledge-inventory-seed.ts ==== */

// #region Imports
import { BRAIN_KNOWLEDGE_INVENTORY_SAFETY_STATUS } from './brain-knowledge-inventory-types';
import type { BlockedAction, BrainKnowledgeInventoryRecord } from './brain-knowledge-inventory-types';
// #endregion

// #region Constants
const COMMON_BLOCKED_ACTIONS: readonly BlockedAction[] = [
  'execute',
  'submit',
  'send',
  'post',
  'file',
  'create_operational_record',
  'create_work_item',
  'create_matter',
  'create_document_ref',
  'persist',
  'provider_action',
  'file_operation',
  'rag_write',
  'knowledge_binding',
  'agent_autonomy',
];

const MANUAL_WORKBENCH_ROUTE = '/internal/manual-preview-workbench';
const PHASE2_STATIC_WARNING = 'תצוגת מלאי ידע סטטית בלבד — לא ידע מחייב, לא פעולה, ולא יצירת משימה.';
// #endregion

// #region Static Data
/** Phase 1 static inventory of knowledge already known to Eldad Brain. */
export const BRAIN_KNOWLEDGE_INVENTORY_PHASE1_RECORDS: readonly BrainKnowledgeInventoryRecord[] = [
  {
    knowledgeId: 'knowledge-manual-workbench-preview-gates-v1',
    title: 'Manual Workbench preview gates',
    domain: 'manual_workbench',
    projectOrMatter: null,
    sourceType: 'route',
    sourceLocation: 'src/pages/internal/manual-preview-workbench',
    whatWasLearned: 'Manual input has static preview summaries for classification, VAT mapping, scanned candidates, and review-gate context.',
    usableFor: ['show safe previews', 'explain missing evidence', 'keep manual review separated from live action'],
    previewOnly: true,
    staticOnly: true,
    bindingKnowledge: false,
    canExecute: false,
    canPersist: false,
    evidenceStatus: 'committed_static',
    confidence: 'high',
    nextSafeUse: 'approval_gate_context',
    blockedActions: COMMON_BLOCKED_ACTIONS,
    relatedCommits: ['a843121', '28ecb17', '5ed94d4', '6f1368b'],
    relatedRoutes: [MANUAL_WORKBENCH_ROUTE],
    sourceTrace: 'Committed Manual Workbench preview chain through scanned approval-gate preview.',
    safetyStatus: BRAIN_KNOWLEDGE_INVENTORY_SAFETY_STATUS,
  },
  {
    knowledgeId: 'knowledge-vat-static-evidence-reconciliation-v1',
    title: 'VAT static evidence and bookkeeping reconciliation examples',
    domain: 'vat_evidence',
    projectOrMatter: 'Eldad VAT examples',
    sourceType: 'static_seed',
    sourceLocation: 'src/work-spine/vat-evidence',
    whatWasLearned: 'Static VAT evidence records include supplier, dates, period, source amounts, VAT values, and confidence.',
    usableFor: ['preview VAT evidence rows', 'show source artifacts', 'avoid claiming full scan coverage'],
    previewOnly: true,
    staticOnly: true,
    bindingKnowledge: false,
    canExecute: false,
    canPersist: false,
    evidenceStatus: 'committed_static',
    confidence: 'high',
    nextSafeUse: 'manual_workbench_hint',
    blockedActions: COMMON_BLOCKED_ACTIONS,
    relatedCommits: ['0c9444c', '28ecb17'],
    relatedRoutes: [MANUAL_WORKBENCH_ROUTE],
    sourceTrace: 'Committed static VAT evidence seed and Manual Workbench wiring.',
    safetyStatus: BRAIN_KNOWLEDGE_INVENTORY_SAFETY_STATUS,
  },
  {
    knowledgeId: 'knowledge-static-scanned-intake-batch-v1',
    title: 'Static scanned intake evidence batch',
    domain: 'scanned_intake',
    projectOrMatter: null,
    sourceType: 'static_seed',
    sourceLocation: 'src/work-spine/scanned-evidence',
    whatWasLearned: 'Scanned documents are represented as static evidence candidates with missing fields and risk preview.',
    usableFor: ['preview scanned candidates', 'show approval-gate context', 'explain why no live intake has run'],
    previewOnly: true,
    staticOnly: true,
    bindingKnowledge: false,
    canExecute: false,
    canPersist: false,
    evidenceStatus: 'committed_static',
    confidence: 'high',
    nextSafeUse: 'approval_gate_context',
    blockedActions: COMMON_BLOCKED_ACTIONS,
    relatedCommits: ['2fb509d', '5ed94d4', '6f1368b'],
    relatedRoutes: [MANUAL_WORKBENCH_ROUTE],
    sourceTrace: 'Committed static scanned batch, Workbench preview, and approval-gate preview.',
    safetyStatus: BRAIN_KNOWLEDGE_INVENTORY_SAFETY_STATUS,
  },
  {
    knowledgeId: 'knowledge-dima-case-work-v1',
    title: 'Dima case work context',
    domain: 'case_work',
    projectOrMatter: 'Dima',
    sourceType: 'case_context',
    sourceLocation: 'known-project-context/dima-case-work',
    whatWasLearned: 'The project contains Dima case work context, but it has not been converted into a stable inventory seed.',
    usableFor: ['future learning queue candidate', 'manual reference planning', 'avoid duplicate discovery prompts'],
    previewOnly: true,
    staticOnly: true,
    bindingKnowledge: false,
    canExecute: false,
    canPersist: false,
    evidenceStatus: 'partial_static',
    confidence: 'medium',
    nextSafeUse: 'learning_queue_candidate',
    blockedActions: COMMON_BLOCKED_ACTIONS,
    relatedCommits: [],
    relatedRoutes: [],
    sourceTrace: 'Known project context named by Eldad; inventory record is a pointer only.',
    safetyStatus: BRAIN_KNOWLEDGE_INVENTORY_SAFETY_STATUS,
  },
  {
    knowledgeId: 'knowledge-tsila-wage-rights-payroll-v1',
    title: 'Tsila wage-rights and payroll context',
    domain: 'wage_rights',
    projectOrMatter: 'Tsila',
    sourceType: 'known_project_context',
    sourceLocation: 'known-project-context/tsila-wage-rights',
    whatWasLearned: 'The project contains wage-rights and payroll learning context, with stable coverage still incomplete.',
    usableFor: ['future learning queue candidate', 'manual review hints', 'domain routing planning'],
    previewOnly: true,
    staticOnly: true,
    bindingKnowledge: false,
    canExecute: false,
    canPersist: false,
    evidenceStatus: 'known_context_only',
    confidence: 'medium',
    nextSafeUse: 'learning_queue_candidate',
    blockedActions: COMMON_BLOCKED_ACTIONS,
    relatedCommits: [],
    relatedRoutes: [],
    sourceTrace: 'Known project context named by Eldad; no live review is represented here.',
    safetyStatus: BRAIN_KNOWLEDGE_INVENTORY_SAFETY_STATUS,
  },
  {
    knowledgeId: 'knowledge-attendance-payroll-calculation-v1',
    title: 'Attendance and payroll calculation context',
    domain: 'payroll_attendance',
    projectOrMatter: null,
    sourceType: 'known_project_context',
    sourceLocation: 'known-project-context/attendance-payroll',
    whatWasLearned: 'Attendance and payroll calculation knowledge exists in project context and needs safe static mapping later.',
    usableFor: ['future learning queue candidate', 'calculation-domain routing planning', 'manual review hints'],
    previewOnly: true,
    staticOnly: true,
    bindingKnowledge: false,
    canExecute: false,
    canPersist: false,
    evidenceStatus: 'partial_static',
    confidence: 'medium',
    nextSafeUse: 'learning_queue_candidate',
    blockedActions: COMMON_BLOCKED_ACTIONS,
    relatedCommits: [],
    relatedRoutes: [],
    sourceTrace: 'Known project context named by Eldad; inventory record does not evaluate calculations.',
    safetyStatus: BRAIN_KNOWLEDGE_INVENTORY_SAFETY_STATUS,
  },
  {
    knowledgeId: 'knowledge-robium-business-plan-salary-bureau-v1',
    title: 'Robium business plan and salary bureau context',
    domain: 'business_planning',
    projectOrMatter: 'Robium',
    sourceType: 'business_plan_context',
    sourceLocation: 'known-project-context/robium-business-plan',
    whatWasLearned: 'Business planning and salary bureau context exists as a pointer for later static inventory review.',
    usableFor: ['future learning queue candidate', 'business planning reference', 'avoid re-learning known planning areas'],
    previewOnly: true,
    staticOnly: true,
    bindingKnowledge: false,
    canExecute: false,
    canPersist: false,
    evidenceStatus: 'known_context_only',
    confidence: 'medium',
    nextSafeUse: 'learning_queue_candidate',
    blockedActions: COMMON_BLOCKED_ACTIONS,
    relatedCommits: [],
    relatedRoutes: [],
    sourceTrace: 'Known business planning context named by Eldad; static pointer only.',
    safetyStatus: BRAIN_KNOWLEDGE_INVENTORY_SAFETY_STATUS,
  },
  {
    knowledgeId: 'knowledge-war-compensation-red-route-v1',
    title: 'War compensation red route knowledge',
    domain: 'war_compensation',
    projectOrMatter: null,
    sourceType: 'known_project_context',
    sourceLocation: 'known-project-context/war-compensation-red-route',
    whatWasLearned: 'War compensation and red route knowledge exists in project context, with static inventory still partial.',
    usableFor: ['future learning queue candidate', 'manual domain hinting', 'safe reference planning'],
    previewOnly: true,
    staticOnly: true,
    bindingKnowledge: false,
    canExecute: false,
    canPersist: false,
    evidenceStatus: 'partial_static',
    confidence: 'medium',
    nextSafeUse: 'learning_queue_candidate',
    blockedActions: COMMON_BLOCKED_ACTIONS,
    relatedCommits: [],
    relatedRoutes: [],
    sourceTrace: 'Known project context named by Eldad; no external step is represented.',
    safetyStatus: BRAIN_KNOWLEDGE_INVENTORY_SAFETY_STATUS,
  },
  {
    knowledgeId: 'knowledge-brain-operating-truth-governance-v1',
    title: 'Brain Operating Truth governance',
    domain: 'brain_governance',
    projectOrMatter: 'Eldad Brain',
    sourceType: 'commit_chain',
    sourceLocation: 'Brain Operating Truth committed context',
    whatWasLearned: 'The Brain must label preview boundaries clearly and keep real-world steps blocked until explicit human review.',
    usableFor: ['governance reference', 'approval-gate wording', 'safe preview boundary checks'],
    previewOnly: true,
    staticOnly: true,
    bindingKnowledge: false,
    canExecute: false,
    canPersist: false,
    evidenceStatus: 'committed_static',
    confidence: 'high',
    nextSafeUse: 'preview_reference_only',
    blockedActions: COMMON_BLOCKED_ACTIONS,
    relatedCommits: ['cda69ee'],
    relatedRoutes: [],
    sourceTrace: 'Committed Brain Operating Truth update after Manual Workbench mapping preview.',
    safetyStatus: BRAIN_KNOWLEDGE_INVENTORY_SAFETY_STATUS,
  },
  {
    knowledgeId: 'knowledge-phase2-proof-of-life-standard-v1',
    title: 'Phase 2 static visual proof checklist pointer',
    domain: 'brain_governance',
    projectOrMatter: 'Eldad Brain',
    sourceType: 'static_artifact',
    sourceLocation: 'commit:07cd8fa',
    whatWasLearned: 'A static visual checklist pointer exists for proof-of-life preview discipline without evaluating correctness.',
    usableFor: [PHASE2_STATIC_WARNING, 'preview checklist reference', 'safe review wording'],
    previewOnly: true,
    staticOnly: true,
    bindingKnowledge: false,
    canExecute: false,
    canPersist: false,
    evidenceStatus: 'committed_static',
    confidence: 'high',
    nextSafeUse: 'preview_reference_only',
    blockedActions: COMMON_BLOCKED_ACTIONS,
    relatedCommits: ['07cd8fa'],
    relatedRoutes: [],
    sourceTrace: `${PHASE2_STATIC_WARNING} Static pointer to committed visual proof checklist context.`,
    safetyStatus: BRAIN_KNOWLEDGE_INVENTORY_SAFETY_STATUS,
  },
  {
    knowledgeId: 'knowledge-phase2-full-brain-blueprint-v1',
    title: 'Phase 2 full Brain blueprint static pointer',
    domain: 'brain_governance',
    projectOrMatter: 'Eldad Brain',
    sourceType: 'static_artifact',
    sourceLocation: 'src/work-spine/blueprint',
    whatWasLearned: 'Blueprint context is represented as static planning material without architecture approval.',
    usableFor: [PHASE2_STATIC_WARNING, 'static architecture reference', 'future learning queue review'],
    previewOnly: true,
    staticOnly: true,
    bindingKnowledge: false,
    canExecute: false,
    canPersist: false,
    evidenceStatus: 'committed_static',
    confidence: 'high',
    nextSafeUse: 'preview_reference_only',
    blockedActions: COMMON_BLOCKED_ACTIONS,
    relatedCommits: [],
    relatedRoutes: [],
    sourceTrace: `${PHASE2_STATIC_WARNING} Static pointer to blueprint source location; no runtime implementation is represented.`,
    safetyStatus: BRAIN_KNOWLEDGE_INVENTORY_SAFETY_STATUS,
  },
  {
    knowledgeId: 'knowledge-phase2-robium-salary-clients-v1',
    title: 'Phase 2 Robium salary bureau client context pointer',
    domain: 'business_planning',
    projectOrMatter: 'Robium',
    sourceType: 'business_plan_context',
    sourceLocation: 'known-project-context/robium-salary-clients',
    whatWasLearned: 'Robium salary bureau client context is represented as a static pointer without payroll calculation.',
    usableFor: [PHASE2_STATIC_WARNING, 'business planning reference', 'future learning queue review'],
    previewOnly: true,
    staticOnly: true,
    bindingKnowledge: false,
    canExecute: false,
    canPersist: false,
    evidenceStatus: 'committed_static',
    confidence: 'medium',
    nextSafeUse: 'learning_queue_candidate',
    blockedActions: COMMON_BLOCKED_ACTIONS,
    relatedCommits: [],
    relatedRoutes: [],
    sourceTrace: `${PHASE2_STATIC_WARNING} Static pointer only; no client-data access or communication is represented.`,
    safetyStatus: BRAIN_KNOWLEDGE_INVENTORY_SAFETY_STATUS,
  },
  {
    knowledgeId: 'knowledge-phase2-vat-static-evidence-v1',
    title: 'Phase 2 VAT static evidence context pointer',
    domain: 'vat_evidence',
    projectOrMatter: 'Eldad VAT examples',
    sourceType: 'static_seed',
    sourceLocation: 'src/work-spine/vat-evidence',
    whatWasLearned: 'VAT static evidence context is available as committed static source references without live bookkeeping access.',
    usableFor: [PHASE2_STATIC_WARNING, 'approval gate context', 'static VAT preview reference'],
    previewOnly: true,
    staticOnly: true,
    bindingKnowledge: false,
    canExecute: false,
    canPersist: false,
    evidenceStatus: 'committed_static',
    confidence: 'high',
    nextSafeUse: 'approval_gate_context',
    blockedActions: COMMON_BLOCKED_ACTIONS,
    relatedCommits: ['0c9444c', '28ecb17'],
    relatedRoutes: [MANUAL_WORKBENCH_ROUTE],
    sourceTrace: `${PHASE2_STATIC_WARNING} Static pointer to committed VAT seed location; no live bookkeeping system access is represented.`,
    safetyStatus: BRAIN_KNOWLEDGE_INVENTORY_SAFETY_STATUS,
  },
  {
    knowledgeId: 'knowledge-phase2-scanned-evidence-batch-v1',
    title: 'Phase 2 scanned evidence batch static pointer',
    domain: 'scanned_intake',
    projectOrMatter: null,
    sourceType: 'static_seed',
    sourceLocation: 'src/work-spine/scanned-evidence',
    whatWasLearned: 'Scanned evidence batch context is partial static candidate context without content verification.',
    usableFor: [PHASE2_STATIC_WARNING, 'missing-field preview context', 'future learning queue review'],
    previewOnly: true,
    staticOnly: true,
    bindingKnowledge: false,
    canExecute: false,
    canPersist: false,
    evidenceStatus: 'partial_static',
    confidence: 'medium',
    nextSafeUse: 'learning_queue_candidate',
    blockedActions: COMMON_BLOCKED_ACTIONS,
    relatedCommits: ['2fb509d', '5ed94d4', '6f1368b'],
    relatedRoutes: [MANUAL_WORKBENCH_ROUTE],
    sourceTrace: `${PHASE2_STATIC_WARNING} Static pointer only; no folder scan or document-content reading is represented.`,
    safetyStatus: BRAIN_KNOWLEDGE_INVENTORY_SAFETY_STATUS,
  },
  {
    knowledgeId: 'knowledge-phase2-knowledge-inventory-preview-v1',
    title: 'Phase 2 knowledge inventory preview planning pointer',
    domain: 'manual_workbench',
    projectOrMatter: 'Eldad Brain',
    sourceType: 'known_project_context',
    sourceLocation: 'planned:manual-workbench-knowledge-inventory-preview',
    whatWasLearned: 'Manual Workbench knowledge inventory preview remains planned static display context only.',
    usableFor: [PHASE2_STATIC_WARNING, 'future Workbench hint planning', 'non-binding inventory preview planning'],
    previewOnly: true,
    staticOnly: true,
    bindingKnowledge: false,
    canExecute: false,
    canPersist: false,
    evidenceStatus: 'partial_static',
    confidence: 'medium',
    nextSafeUse: 'learning_queue_candidate',
    blockedActions: COMMON_BLOCKED_ACTIONS,
    relatedCommits: [],
    relatedRoutes: [],
    sourceTrace: `${PHASE2_STATIC_WARNING} Static planning pointer only; no binding knowledge is represented.`,
    safetyStatus: BRAIN_KNOWLEDGE_INVENTORY_SAFETY_STATUS,
  },
];
// #endregion
