/* ==== FILE: src/work-spine/build-progress/brain-build-progress-console-seed.ts ==== */

// #region Imports
import {
  BRAIN_BUILD_BLOCKED_ACTIONS,
  BRAIN_BUILD_PROGRESS_SAFETY_STATUS,
} from './brain-build-progress-console-types';
import type { BrainBuildProgressItem } from './brain-build-progress-console-types';
// #endregion

// #region Constants
export const BRAIN_BUILD_PROGRESS_ROUTE = '/internal/brain-build-progress';
export const MANUAL_WORKBENCH_ROUTE = '/internal/manual-preview-workbench';
export const BRAIN_BUILD_PROGRESS_WARNING =
  'התקדמות בנייה בלבד — לא מוכנות תפעולית, לא אימות מקצועי, לא חיבור חי, ולא הרשאה לפעול.';
export const BRAIN_BUILD_LATEST_CHANGE_WARNING =
  'סיכום שינוי סטטי בלבד — לא פריסה חיה, לא מוכנות תפעולית, לא אימות מקור, לא חיבור ספקים, ולא הרשאה לפעול.';

const COMMON_BLOCKED = [
  'no live source access',
  'no source content reading',
  'no task or record creation',
  'no filing or submission',
  'no retained state write',
] as const;

const proofScenario = (input: string, expectedVisibleResult: string) => ({
  input,
  expectedVisibleResult,
});
// #endregion

// #region Static Data
/** Latest committed build-state summary shown above the full progress history. */
export const BRAIN_BUILD_LATEST_CHANGE_SUMMARY = {
  title: 'תיקון עברית מלא למסך התקדמות בניית המוח',
  relatedCommit: '0132154',
  whereToSee: BRAIN_BUILD_PROGRESS_ROUTE,
  whatChanged: 'המסך עבר לתצוגה עברית מלאה: כותרות, מדדים, סטטוסים, שדות, שמות פריטים ופעולות חסומות.',
  proofOfLife: `המסך מציג UI עברי מלא ושומר על האזהרה: ${BRAIN_BUILD_PROGRESS_WARNING}`,
  stillBlocked: [
    'אין פעולה חיה',
    'אין שמירה',
    'אין חיבור ספק',
    'אין יצירת משימה',
    'אין יצירת תיק',
    'אין DocumentRef',
    'אין persistence',
  ],
  nextSafeStep: 'ביקורת חזותית בלבד לפני הרחבה נוספת.',
  safetyStatus: 'סיכום התקדמות לקריאה בלבד',
  safetyNotes: [
    'מידע בנייה פנימי אמיתי לקריאה בלבד',
    'לא מוכנות תפעולית',
    'לא אימות מקור',
    'אין חיבור ספקים',
    'אין הרשאת פעולה או שמירה',
  ],
} as const;

/** Static build progress checkpoints for the temporary Brain Build Progress Console. */
export const BRAIN_BUILD_PROGRESS_ITEMS: readonly BrainBuildProgressItem[] = [
  {
    progressItemId: 'progress-vat-mapping-table-preview-v1',
    title: 'תצוגת טבלת מיפוי מע״מ',
    domain: 'vat',
    layer: 'manual_workbench',
    relatedCommit: 'a843121',
    visibleRoute: MANUAL_WORKBENCH_ROUTE,
    proofScenario: proofScenario('מע״מ מייבן בזק', 'מוצגת טבלת מיפוי מע״מ סטטית במסך הידני.'),
    currentStatus: 'built_and_visible',
    proofStatus: 'visible_static_preview',
    surfaceClassification: 'preview_only',
    whatWasBuilt: 'נוספה תצוגת טבלת מיפוי מע״מ לקריאה בלבד במסך הידני.',
    whatEldadCanSee: 'אלדד רואה שורות מיפוי מע״מ וסימוני נתונים חסרים במסלול הידני.',
    whatIsStillBlocked: COMMON_BLOCKED,
    nextSafeStep: 'להשאיר כהקשר תצוגה בלבד עד פתיחת שער ביקורת נפרד.',
    responsibleAgent: 'Codex ראשי',
    safetyStatus: BRAIN_BUILD_PROGRESS_SAFETY_STATUS,
    blockedActions: BRAIN_BUILD_BLOCKED_ACTIONS,
  },
  {
    progressItemId: 'progress-static-vat-evidence-seed-v1',
    title: 'מאגר ראיות מע״מ סטטי',
    domain: 'vat',
    layer: 'static_evidence',
    relatedCommit: '0c9444c',
    visibleRoute: MANUAL_WORKBENCH_ROUTE,
    proofScenario: proofScenario('בזק מע״מ', 'שורות מאגר מע״מ סטטי מוצגות דרך תצוגת המסך הידני.'),
    currentStatus: 'built_not_visible',
    proofStatus: 'static_reference_recorded',
    surfaceClassification: 'preview_only',
    whatWasBuilt: 'נוסף מאגר ראיות מע״מ סטטי כהפניה מצומצמת.',
    whatEldadCanSee: 'אלדד רואה את המאגר רק כאשר משטח תצוגה מציג שורות תואמות.',
    whatIsStillBlocked: COMMON_BLOCKED,
    nextSafeStep: 'להשתמש רק כהפניה סטטית לתצוגה.',
    responsibleAgent: 'Codex ראשי',
    safetyStatus: BRAIN_BUILD_PROGRESS_SAFETY_STATUS,
    blockedActions: BRAIN_BUILD_BLOCKED_ACTIONS,
  },
  {
    progressItemId: 'progress-scanned-evidence-batch-v1',
    title: 'אצוות ראיות סריקה סטטית',
    domain: 'scanned_evidence',
    layer: 'scanned_intake',
    relatedCommit: '2fb509d',
    visibleRoute: MANUAL_WORKBENCH_ROUTE,
    proofScenario: proofScenario('סריקות', 'מועמדי ראיות סריקה סטטיים מוצגים במסך הידני כאשר יש התאמת רמזים.'),
    currentStatus: 'built_not_visible',
    proofStatus: 'static_reference_recorded',
    surfaceClassification: 'preview_only',
    whatWasBuilt: 'נוספה אצוות מועמדי ראיות סריקה סטטית.',
    whatEldadCanSee: 'אלדד רואה שורות מועמדות מייצגות כאשר רמזי התצוגה מתאימים.',
    whatIsStillBlocked: COMMON_BLOCKED,
    nextSafeStep: 'להשאיר הרחבת ראיות סריקה מאחורי בדיקה סטטית.',
    responsibleAgent: 'Codex ראשי',
    safetyStatus: BRAIN_BUILD_PROGRESS_SAFETY_STATUS,
    blockedActions: BRAIN_BUILD_BLOCKED_ACTIONS,
  },
  {
    progressItemId: 'progress-scanned-batch-preview-v1',
    title: 'תצוגת אצוות סריקות',
    domain: 'scanned_evidence',
    layer: 'manual_workbench',
    relatedCommit: '5ed94d4',
    visibleRoute: MANUAL_WORKBENCH_ROUTE,
    proofScenario: proofScenario('סריקות דימה', 'המסך הידני מציג מועמדי סריקה סטטיים.'),
    currentStatus: 'built_and_visible',
    proofStatus: 'visible_static_preview',
    surfaceClassification: 'preview_only',
    whatWasBuilt: 'נוספה למסך הידני תצוגת אצוות סריקות סטטית לקריאה בלבד.',
    whatEldadCanSee: 'אלדד רואה סוג מועמד, שדות חסרים, עקבת מקור ורמת ביטחון.',
    whatIsStillBlocked: COMMON_BLOCKED,
    nextSafeStep: 'לבחון פלט חזותי בלבד.',
    responsibleAgent: 'Codex ראשי',
    safetyStatus: BRAIN_BUILD_PROGRESS_SAFETY_STATUS,
    blockedActions: BRAIN_BUILD_BLOCKED_ACTIONS,
  },
  {
    progressItemId: 'progress-approval-gate-preview-v1',
    title: 'תצוגת שער אישור',
    domain: 'approval',
    layer: 'approval_gate',
    relatedCommit: '6f1368b',
    visibleRoute: MANUAL_WORKBENCH_ROUTE,
    proofScenario: proofScenario('סריקות דימה', 'טקסט שער אישור מוצג תחת מועמדי סריקה.'),
    currentStatus: 'built_and_visible',
    proofStatus: 'visible_static_preview',
    surfaceClassification: 'preview_only',
    whatWasBuilt: 'נוספה תצוגת שער אישור פסיבית תחת מועמדי סריקה.',
    whatEldadCanSee: 'אלדד רואה הקשר בדיקה מוצע ושדות חסרים.',
    whatIsStillBlocked: COMMON_BLOCKED,
    nextSafeStep: 'להשאיר את שפת האישור פסיבית.',
    responsibleAgent: 'Codex ראשי',
    safetyStatus: BRAIN_BUILD_PROGRESS_SAFETY_STATUS,
    blockedActions: BRAIN_BUILD_BLOCKED_ACTIONS,
  },
  {
    progressItemId: 'progress-knowledge-inventory-phase1-v1',
    title: 'מלאי ידע שלב 1',
    domain: 'knowledge',
    layer: 'knowledge_inventory',
    relatedCommit: 'a2011a6',
    visibleRoute: MANUAL_WORKBENCH_ROUTE,
    proofScenario: proofScenario('צילה שכר', 'הקשר מלאי ידע סטטי מוצג כאשר מילות הקלט מתאימות.'),
    currentStatus: 'built_not_visible',
    proofStatus: 'static_reference_recorded',
    surfaceClassification: 'preview_only',
    whatWasBuilt: 'נוספו רשומות מלאי ידע סטטיות של שלב 1.',
    whatEldadCanSee: 'אלדד רואה הקשר מלאי דרך משטח התצוגה שנוסף לאחר מכן.',
    whatIsStillBlocked: COMMON_BLOCKED,
    nextSafeStep: 'להשתמש כהקשר מצביע בלבד.',
    responsibleAgent: 'Codex ראשי',
    safetyStatus: BRAIN_BUILD_PROGRESS_SAFETY_STATUS,
    blockedActions: BRAIN_BUILD_BLOCKED_ACTIONS,
  },
  {
    progressItemId: 'progress-knowledge-inventory-preview-v1',
    title: 'תצוגת מלאי ידע',
    domain: 'knowledge',
    layer: 'manual_workbench',
    relatedCommit: '31facca',
    visibleRoute: MANUAL_WORKBENCH_ROUTE,
    proofScenario: proofScenario('מע״מ מייבן בזק', 'רשומות ידע סטטיות קשורות מוצגות במסך הידני.'),
    currentStatus: 'built_and_visible',
    proofStatus: 'visible_static_preview',
    surfaceClassification: 'preview_only',
    whatWasBuilt: 'נוספה למסך הידני תצוגת ידע קשור.',
    whatEldadCanSee: 'אלדד רואה סטטוס ראיה, מיקום מקור ופעולות חסומות.',
    whatIsStillBlocked: COMMON_BLOCKED,
    nextSafeStep: 'לבקר ניסוח לפני הרחבת רשומות.',
    responsibleAgent: 'Codex ראשי',
    safetyStatus: BRAIN_BUILD_PROGRESS_SAFETY_STATUS,
    blockedActions: BRAIN_BUILD_BLOCKED_ACTIONS,
  },
  {
    progressItemId: 'progress-static-visual-proof-checklist-v1',
    title: 'רשימת בדיקת הוכחת תצוגה סטטית',
    domain: 'proof',
    layer: 'proof_inventory',
    relatedCommit: '07cd8fa',
    visibleRoute: null,
    proofScenario: proofScenario('commit:07cd8fa', 'רשימת בדיקת הוכחת תצוגה סטטית קיימת כהפניית בקרת פרויקט.'),
    currentStatus: 'built_not_visible',
    proofStatus: 'not_visible_as_screen',
    surfaceClassification: 'static_visual',
    whatWasBuilt: 'נוספה רשימת בדיקה סטטית להוכחת תצוגה.',
    whatEldadCanSee: 'אלדד רואה את ההשפעה שלה רק דרך סיכומי התקדמות מאוחרים יותר.',
    whatIsStillBlocked: COMMON_BLOCKED,
    nextSafeStep: 'למפות משטחים חזותיים לפני עבודת ביקורת תצוגה.',
    responsibleAgent: 'Codex ראשי',
    safetyStatus: BRAIN_BUILD_PROGRESS_SAFETY_STATUS,
    blockedActions: BRAIN_BUILD_BLOCKED_ACTIONS,
  },
  {
    progressItemId: 'progress-phase2-safe-knowledge-candidates-v1',
    title: 'מועמדי ידע בטוחים שלב 2',
    domain: 'knowledge',
    layer: 'knowledge_inventory',
    relatedCommit: 'cd122de',
    visibleRoute: MANUAL_WORKBENCH_ROUTE,
    proofScenario: proofScenario('Robium לשכת שכר', 'מועמדי שלב 2 סטטיים מוצגים כהקשר מלאי.'),
    currentStatus: 'built_not_visible',
    proofStatus: 'static_reference_recorded',
    surfaceClassification: 'preview_only',
    whatWasBuilt: 'נוספו שש רשומות מועמדי ידע לשלב 2 במסגרת סטטית.',
    whatEldadCanSee: 'אלדד רואה אותן רק כהקשר מצביע סטטי.',
    whatIsStillBlocked: COMMON_BLOCKED,
    nextSafeStep: 'להשאיר מועמדים מאחורי ביקורת לפני שימוש מאוחר יותר.',
    responsibleAgent: 'Codex ראשי',
    safetyStatus: BRAIN_BUILD_PROGRESS_SAFETY_STATUS,
    blockedActions: BRAIN_BUILD_BLOCKED_ACTIONS,
  },
  {
    progressItemId: 'progress-hypothetical-task-shape-preview-v1',
    title: 'תצוגת צורת משימה היפותטית',
    domain: 'scanned_evidence',
    layer: 'manual_workbench',
    relatedCommit: '160f271',
    visibleRoute: MANUAL_WORKBENCH_ROUTE,
    proofScenario: proofScenario('סריקות דימה', 'תצוגת צורת משימה היפותטית מוצגת תחת מועמדי סריקה תואמים.'),
    currentStatus: 'built_and_visible',
    proofStatus: 'visible_static_preview',
    surfaceClassification: 'preview_only',
    whatWasBuilt: 'נוספה תצוגת צורת משימה היפותטית לסריקות.',
    whatEldadCanSee: 'אלדד רואה דגלי יכולת שליליים ופעולות חסומות.',
    whatIsStillBlocked: COMMON_BLOCKED,
    nextSafeStep: 'להשאיר את צורת המשימה נפרדת מאובייקטים אמיתיים.',
    responsibleAgent: 'Codex ראשי',
    safetyStatus: BRAIN_BUILD_PROGRESS_SAFETY_STATUS,
    blockedActions: BRAIN_BUILD_BLOCKED_ACTIONS,
  },
  {
    progressItemId: 'progress-intake-signal-summary-v1',
    title: 'סיכום רמזי קלט',
    domain: 'intake',
    layer: 'manual_workbench',
    relatedCommit: 'ee3a06f',
    visibleRoute: MANUAL_WORKBENCH_ROUTE,
    proofScenario: proofScenario('צילה שכר', 'סיכום רמזי קלט ידני מציג רמזי טקסט ושלבים חסומים.'),
    currentStatus: 'built_and_visible',
    proofStatus: 'visible_static_preview',
    surfaceClassification: 'preview_only',
    whatWasBuilt: 'נוסף סיכום רמזי קלט ידני לקריאה בלבד.',
    whatEldadCanSee: 'אלדד רואה ניסוח רמזים ללא טענות תוכן.',
    whatIsStillBlocked: COMMON_BLOCKED,
    nextSafeStep: 'להשאיר את שפת הסיכום מוגבלת לרמזי טקסט ידניים.',
    responsibleAgent: 'Codex ראשי',
    safetyStatus: BRAIN_BUILD_PROGRESS_SAFETY_STATUS,
    blockedActions: BRAIN_BUILD_BLOCKED_ACTIONS,
  },
  {
    progressItemId: 'progress-visual-brain-surface-inventory-v1',
    title: 'מלאי משטחי מוח חזותיים',
    domain: 'visual_surface',
    layer: 'surface_inventory',
    relatedCommit: 'edf165d',
    visibleRoute: null,
    proofScenario: proofScenario('commit:edf165d', 'רשומות מלאי משטחים חזותיים סטטיות קיימות כהקשר בקרת פרויקט.'),
    currentStatus: 'built_not_visible',
    proofStatus: 'not_visible_as_screen',
    surfaceClassification: 'static_visual',
    whatWasBuilt: 'נוסף מלאי משטחי מוח חזותיים סטטי.',
    whatEldadCanSee: 'אלדד רואה אותו דרך מסך ההתקדמות הזה לאחר שהוא מוצג.',
    whatIsStillBlocked: COMMON_BLOCKED,
    nextSafeStep: 'להשתמש במפה הזו לבחירת פרוסת ביקורת חזותית מאוחרת יותר.',
    responsibleAgent: 'Codex ראשי',
    safetyStatus: BRAIN_BUILD_PROGRESS_SAFETY_STATUS,
    blockedActions: BRAIN_BUILD_BLOCKED_ACTIONS,
  },
];
// #endregion
