/* ==== FILE: src/work-spine/build-progress/brain-build-progress-console-seed.ts ==== */

// #region Imports
import {
  BRAIN_BUILD_BLOCKED_ACTIONS,
  BRAIN_BUILD_PROGRESS_SAFETY_STATUS,
} from './brain-build-progress-console-types';
import type { BrainBuildProgressItem } from './brain-build-progress-console-types';
// #endregion

// #region Constants
export const BRAIN_BUILD_PROGRESS_ROUTE = '/internal/brain-build-progress';
export const MANUAL_WORKBENCH_ROUTE = '/internal/manual-preview-workbench';
export const BRAIN_BUILD_PROGRESS_WARNING =
  'התקדמות בנייה בלבד — לא מוכנות תפעולית, לא אימות מקצועי, לא חיבור חי, ולא הרשאה לפעול.';

const COMMON_BLOCKED = [
  'no live source access',
  'no source content reading',
  'no task or record creation',
  'no filing or submission',
  'no retained state write',
] as const;

const proofScenario = (input: string, expectedVisibleResult: string) => ({
  input,
  expectedVisibleResult,
});
// #endregion

// #region Static Data
/** Static build progress checkpoints for the temporary Brain Build Progress Console. */
export const BRAIN_BUILD_PROGRESS_ITEMS: readonly BrainBuildProgressItem[] = [
  {
    progressItemId: 'progress-vat-mapping-table-preview-v1',
    title: 'VAT mapping table preview',
    domain: 'vat',
    layer: 'manual_workbench',
    relatedCommit: 'a843121',
    visibleRoute: MANUAL_WORKBENCH_ROUTE,
    proofScenario: proofScenario('מע״מ מייבן בזק', 'Manual Workbench shows a static VAT mapping table preview.'),
    currentStatus: 'built_and_visible',
    proofStatus: 'visible_static_preview',
    surfaceClassification: 'preview_only',
    whatWasBuilt: 'A read-only VAT mapping table preview was added to Manual Workbench.',
    whatEldadCanSee: 'Eldad can see VAT mapping rows and missing-data markers in the manual route.',
    whatIsStillBlocked: COMMON_BLOCKED,
    nextSafeStep: 'Keep as preview context until a separate audit gate is opened.',
    responsibleAgent: 'Main Codex',
    safetyStatus: BRAIN_BUILD_PROGRESS_SAFETY_STATUS,
    blockedActions: BRAIN_BUILD_BLOCKED_ACTIONS,
  },
  {
    progressItemId: 'progress-static-vat-evidence-seed-v1',
    title: 'Static VAT Evidence Seed',
    domain: 'vat',
    layer: 'static_evidence',
    relatedCommit: '0c9444c',
    visibleRoute: MANUAL_WORKBENCH_ROUTE,
    proofScenario: proofScenario('בזק מע״מ', 'Static VAT seed rows can be shown through the Workbench preview.'),
    currentStatus: 'built_not_visible',
    proofStatus: 'static_reference_recorded',
    surfaceClassification: 'preview_only',
    whatWasBuilt: 'A static VAT evidence seed was added as a narrow reference set.',
    whatEldadCanSee: 'Eldad can see the seed only when a preview surface renders matching rows.',
    whatIsStillBlocked: COMMON_BLOCKED,
    nextSafeStep: 'Use only as static preview reference.',
    responsibleAgent: 'Main Codex',
    safetyStatus: BRAIN_BUILD_PROGRESS_SAFETY_STATUS,
    blockedActions: BRAIN_BUILD_BLOCKED_ACTIONS,
  },
  {
    progressItemId: 'progress-scanned-evidence-batch-v1',
    title: 'Scanned Evidence Batch',
    domain: 'scanned_evidence',
    layer: 'scanned_intake',
    relatedCommit: '2fb509d',
    visibleRoute: MANUAL_WORKBENCH_ROUTE,
    proofScenario: proofScenario('סריקות', 'Static scanned evidence candidates can appear in Manual Workbench.'),
    currentStatus: 'built_not_visible',
    proofStatus: 'static_reference_recorded',
    surfaceClassification: 'preview_only',
    whatWasBuilt: 'A static scanned evidence candidate batch was added.',
    whatEldadCanSee: 'Eldad can see representative scanned candidate rows when preview signals match.',
    whatIsStillBlocked: COMMON_BLOCKED,
    nextSafeStep: 'Keep scanned evidence expansion behind static review.',
    responsibleAgent: 'Main Codex',
    safetyStatus: BRAIN_BUILD_PROGRESS_SAFETY_STATUS,
    blockedActions: BRAIN_BUILD_BLOCKED_ACTIONS,
  },
  {
    progressItemId: 'progress-scanned-batch-preview-v1',
    title: 'Scanned batch preview',
    domain: 'scanned_evidence',
    layer: 'manual_workbench',
    relatedCommit: '5ed94d4',
    visibleRoute: MANUAL_WORKBENCH_ROUTE,
    proofScenario: proofScenario('סריקות דימה', 'Workbench shows static scanned candidate previews.'),
    currentStatus: 'built_and_visible',
    proofStatus: 'visible_static_preview',
    surfaceClassification: 'preview_only',
    whatWasBuilt: 'Manual Workbench gained a read-only static scanned batch preview.',
    whatEldadCanSee: 'Eldad can see candidate kind, missing fields, source trace, and confidence.',
    whatIsStillBlocked: COMMON_BLOCKED,
    nextSafeStep: 'Review visual output only.',
    responsibleAgent: 'Main Codex',
    safetyStatus: BRAIN_BUILD_PROGRESS_SAFETY_STATUS,
    blockedActions: BRAIN_BUILD_BLOCKED_ACTIONS,
  },
  {
    progressItemId: 'progress-approval-gate-preview-v1',
    title: 'Approval Gate Preview',
    domain: 'approval',
    layer: 'approval_gate',
    relatedCommit: '6f1368b',
    visibleRoute: MANUAL_WORKBENCH_ROUTE,
    proofScenario: proofScenario('סריקות דימה', 'Approval preview text appears under scanned candidates.'),
    currentStatus: 'built_and_visible',
    proofStatus: 'visible_static_preview',
    surfaceClassification: 'preview_only',
    whatWasBuilt: 'A passive approval-gate preview was added under scanned candidates.',
    whatEldadCanSee: 'Eldad can see proposed review context and missing fields.',
    whatIsStillBlocked: COMMON_BLOCKED,
    nextSafeStep: 'Keep approval language passive.',
    responsibleAgent: 'Main Codex',
    safetyStatus: BRAIN_BUILD_PROGRESS_SAFETY_STATUS,
    blockedActions: BRAIN_BUILD_BLOCKED_ACTIONS,
  },
  {
    progressItemId: 'progress-knowledge-inventory-phase1-v1',
    title: 'Knowledge Inventory Phase 1',
    domain: 'knowledge',
    layer: 'knowledge_inventory',
    relatedCommit: 'a2011a6',
    visibleRoute: MANUAL_WORKBENCH_ROUTE,
    proofScenario: proofScenario('צילה שכר', 'Static knowledge inventory context can be displayed when terms match.'),
    currentStatus: 'built_not_visible',
    proofStatus: 'static_reference_recorded',
    surfaceClassification: 'preview_only',
    whatWasBuilt: 'Phase 1 static knowledge inventory records were added.',
    whatEldadCanSee: 'Eldad can see inventory context through the later preview surface.',
    whatIsStillBlocked: COMMON_BLOCKED,
    nextSafeStep: 'Use as pointer context only.',
    responsibleAgent: 'Main Codex',
    safetyStatus: BRAIN_BUILD_PROGRESS_SAFETY_STATUS,
    blockedActions: BRAIN_BUILD_BLOCKED_ACTIONS,
  },
  {
    progressItemId: 'progress-knowledge-inventory-preview-v1',
    title: 'Knowledge Inventory Preview',
    domain: 'knowledge',
    layer: 'manual_workbench',
    relatedCommit: '31facca',
    visibleRoute: MANUAL_WORKBENCH_ROUTE,
    proofScenario: proofScenario('מע״מ מייבן בזק', 'Related static knowledge records appear in Manual Workbench.'),
    currentStatus: 'built_and_visible',
    proofStatus: 'visible_static_preview',
    surfaceClassification: 'preview_only',
    whatWasBuilt: 'Manual Workbench gained a related knowledge preview.',
    whatEldadCanSee: 'Eldad can see evidence status, source location, and blocked actions.',
    whatIsStillBlocked: COMMON_BLOCKED,
    nextSafeStep: 'Audit wording before expanding records.',
    responsibleAgent: 'Main Codex',
    safetyStatus: BRAIN_BUILD_PROGRESS_SAFETY_STATUS,
    blockedActions: BRAIN_BUILD_BLOCKED_ACTIONS,
  },
  {
    progressItemId: 'progress-static-visual-proof-checklist-v1',
    title: 'Static Visual Proof Checklist',
    domain: 'proof',
    layer: 'proof_inventory',
    relatedCommit: '07cd8fa',
    visibleRoute: null,
    proofScenario: proofScenario('commit:07cd8fa', 'Static visual proof checklist exists as a project-control reference.'),
    currentStatus: 'built_not_visible',
    proofStatus: 'not_visible_as_screen',
    surfaceClassification: 'static_visual',
    whatWasBuilt: 'A static checklist for visual proof was added.',
    whatEldadCanSee: 'Eldad can see its effect only through later progress summaries.',
    whatIsStillBlocked: COMMON_BLOCKED,
    nextSafeStep: 'Map visible surfaces before visual audit work.',
    responsibleAgent: 'Main Codex',
    safetyStatus: BRAIN_BUILD_PROGRESS_SAFETY_STATUS,
    blockedActions: BRAIN_BUILD_BLOCKED_ACTIONS,
  },
  {
    progressItemId: 'progress-phase2-safe-knowledge-candidates-v1',
    title: 'Phase 2 Safe Knowledge Candidates',
    domain: 'knowledge',
    layer: 'knowledge_inventory',
    relatedCommit: 'cd122de',
    visibleRoute: MANUAL_WORKBENCH_ROUTE,
    proofScenario: proofScenario('Robium לשכת שכר', 'Static Phase 2 candidates can appear as inventory context.'),
    currentStatus: 'built_not_visible',
    proofStatus: 'static_reference_recorded',
    surfaceClassification: 'preview_only',
    whatWasBuilt: 'Six safe Phase 2 knowledge candidate records were added.',
    whatEldadCanSee: 'Eldad can see them only as static pointer context.',
    whatIsStillBlocked: COMMON_BLOCKED,
    nextSafeStep: 'Keep candidates behind audit before any later use.',
    responsibleAgent: 'Main Codex',
    safetyStatus: BRAIN_BUILD_PROGRESS_SAFETY_STATUS,
    blockedActions: BRAIN_BUILD_BLOCKED_ACTIONS,
  },
  {
    progressItemId: 'progress-hypothetical-task-shape-preview-v1',
    title: 'Hypothetical Scanned Task Shape Preview',
    domain: 'scanned_evidence',
    layer: 'manual_workbench',
    relatedCommit: '160f271',
    visibleRoute: MANUAL_WORKBENCH_ROUTE,
    proofScenario: proofScenario('סריקות דימה', 'Hypothetical task-shape preview appears under matched scanned candidates.'),
    currentStatus: 'built_and_visible',
    proofStatus: 'visible_static_preview',
    surfaceClassification: 'preview_only',
    whatWasBuilt: 'A hypothetical scanned task-shape preview was added.',
    whatEldadCanSee: 'Eldad can see false capability flags and blocked actions.',
    whatIsStillBlocked: COMMON_BLOCKED,
    nextSafeStep: 'Keep task shape separate from real objects.',
    responsibleAgent: 'Main Codex',
    safetyStatus: BRAIN_BUILD_PROGRESS_SAFETY_STATUS,
    blockedActions: BRAIN_BUILD_BLOCKED_ACTIONS,
  },
  {
    progressItemId: 'progress-intake-signal-summary-v1',
    title: 'Intake Signal Summary',
    domain: 'intake',
    layer: 'manual_workbench',
    relatedCommit: 'ee3a06f',
    visibleRoute: MANUAL_WORKBENCH_ROUTE,
    proofScenario: proofScenario('צילה שכר', 'Manual signal summary explains text signals and blocked steps.'),
    currentStatus: 'built_and_visible',
    proofStatus: 'visible_static_preview',
    surfaceClassification: 'preview_only',
    whatWasBuilt: 'A read-only manual signal summary was added.',
    whatEldadCanSee: 'Eldad can see signal wording without content claims.',
    whatIsStillBlocked: COMMON_BLOCKED,
    nextSafeStep: 'Keep summary language limited to manual text signals.',
    responsibleAgent: 'Main Codex',
    safetyStatus: BRAIN_BUILD_PROGRESS_SAFETY_STATUS,
    blockedActions: BRAIN_BUILD_BLOCKED_ACTIONS,
  },
  {
    progressItemId: 'progress-visual-brain-surface-inventory-v1',
    title: 'Visual Brain Surface Inventory',
    domain: 'visual_surface',
    layer: 'surface_inventory',
    relatedCommit: 'edf165d',
    visibleRoute: null,
    proofScenario: proofScenario('commit:edf165d', 'Static visual surface inventory records exist as project-control context.'),
    currentStatus: 'built_not_visible',
    proofStatus: 'not_visible_as_screen',
    surfaceClassification: 'static_visual',
    whatWasBuilt: 'A static visual surface inventory was added.',
    whatEldadCanSee: 'Eldad can see it through this progress console once rendered.',
    whatIsStillBlocked: COMMON_BLOCKED,
    nextSafeStep: 'Use this map to choose a later visual audit slice.',
    responsibleAgent: 'Main Codex',
    safetyStatus: BRAIN_BUILD_PROGRESS_SAFETY_STATUS,
    blockedActions: BRAIN_BUILD_BLOCKED_ACTIONS,
  },
];
// #endregion
