/* ==== FILE: src/work-spine/agent-process-map/agent-process-assignment-seed.ts ==== */

// #region Imports
import type { AgentProcessAssignment } from './agent-process-assignment-types';
// #endregion

// #region Constants
/** Hebrew label for the static Stage 21D assignment map. */
export const AGENT_PROCESS_ASSIGNMENT_LABEL = 'מפת שיוך סוכנים לתהליכים';

/** Static warning for the Stage 21D assignment map. */
export const AGENT_PROCESS_ASSIGNMENT_WARNING =
  'מפת שיוך סטטית בלבד — אין סוכנים רצים, אין הפעלת תהליכים, אין שמירה, ואין יצירת ישויות.';
// #endregion

// #region Static Data
/** Static assignment rows between the 30-agent workforce and 13 Process Library blueprints. */
export const AGENT_PROCESS_ASSIGNMENTS: readonly AgentProcessAssignment[] = [
  { assignmentId: 'assignment-process-institutional-reports-v1', processId: 'process-institutional-reports', primaryAgentIds: ['document-export-shape-agent'], supportingAgentIds: ['knowledge-inventory-agent', 'ceo-brief-agent'], reviewAgentIds: ['safety-qa-agent', 'evidence-qa-agent'], requiredGate: 'שער תכנון דוחות מוסדיים סטטי', allowedMode: 'static_preview_only', operationalExecution: false, canRun: false, canPersist: false, canCreateMatter: false, canCreateWorkItem: false, canCreateDocumentRef: false },
  { assignmentId: 'assignment-process-penalty-cancellation-v1', processId: 'process-penalty-cancellation', primaryAgentIds: ['income-tax-router-agent'], supportingAgentIds: ['missing-fields-agent', 'letter-shape-agent', 'source-trace-agent'], reviewAgentIds: ['wording-risk-agent', 'evidence-qa-agent'], requiredGate: 'שער ביקורת ביטול קנסות', allowedMode: 'static_preview_only', operationalExecution: false, canRun: false, canPersist: false, canCreateMatter: false, canCreateWorkItem: false, canCreateDocumentRef: false },
  { assignmentId: 'assignment-process-declaration-of-capital-v1', processId: 'process-declaration-of-capital', primaryAgentIds: ['capital-statement-context-agent'], supportingAgentIds: ['client-context-agent', 'duplicate-risk-agent', 'source-trace-agent'], reviewAgentIds: ['evidence-qa-agent', 'safety-qa-agent'], requiredGate: 'שער הצהרת הון סטטי', allowedMode: 'static_preview_only', operationalExecution: false, canRun: false, canPersist: false, canCreateMatter: false, canCreateWorkItem: false, canCreateDocumentRef: false },
  { assignmentId: 'assignment-process-vat-report-v1', processId: 'process-vat-report', primaryAgentIds: ['vat-evidence-agent'], supportingAgentIds: ['vat-external-context-agent', 'supplier-vat-fields-agent'], reviewAgentIds: ['safety-qa-agent', 'evidence-qa-agent'], requiredGate: 'שער ביקורת מע״מ', allowedMode: 'static_preview_only', operationalExecution: false, canRun: false, canPersist: false, canCreateMatter: false, canCreateWorkItem: false, canCreateDocumentRef: false },
  { assignmentId: 'assignment-process-attendance-v1', processId: 'process-attendance', primaryAgentIds: ['attendance-payroll-context-agent'], supportingAgentIds: ['employee-lifecycle-agent', 'tsila-context-agent'], reviewAgentIds: ['labor-law-context-agent', 'safety-qa-agent'], requiredGate: 'שער נוכחות ושכר', allowedMode: 'static_preview_only', operationalExecution: false, canRun: false, canPersist: false, canCreateMatter: false, canCreateWorkItem: false, canCreateDocumentRef: false },
  { assignmentId: 'assignment-process-attendance-agents-v1', processId: 'process-attendance-agents', primaryAgentIds: ['agent-workforce-planner'], supportingAgentIds: ['visual-surface-audit-agent', 'attendance-payroll-context-agent'], reviewAgentIds: ['safety-qa-agent', 'wording-risk-agent'], requiredGate: 'שער תכנון סוכני נוכחות', allowedMode: 'static_preview_only', operationalExecution: false, canRun: false, canPersist: false, canCreateMatter: false, canCreateWorkItem: false, canCreateDocumentRef: false },
  { assignmentId: 'assignment-process-payroll-processing-v1', processId: 'process-payroll-processing', primaryAgentIds: ['attendance-payroll-context-agent'], supportingAgentIds: ['labor-law-context-agent', 'tsila-context-agent', 'missing-fields-agent'], reviewAgentIds: ['evidence-qa-agent', 'safety-qa-agent'], requiredGate: 'שער שכר סטטי', allowedMode: 'static_preview_only', operationalExecution: false, canRun: false, canPersist: false, canCreateMatter: false, canCreateWorkItem: false, canCreateDocumentRef: false },
  { assignmentId: 'assignment-process-worklaw-v1', processId: 'process-worklaw', primaryAgentIds: ['labor-law-context-agent'], supportingAgentIds: ['employee-lifecycle-agent', 'source-trace-agent'], reviewAgentIds: ['wording-risk-agent', 'safety-qa-agent'], requiredGate: 'שער דיני עבודה', allowedMode: 'static_preview_only', operationalExecution: false, canRun: false, canPersist: false, canCreateMatter: false, canCreateWorkItem: false, canCreateDocumentRef: false },
  { assignmentId: 'assignment-process-expert-opinion-v1', processId: 'process-expert-opinion', primaryAgentIds: ['document-kind-preview-agent'], supportingAgentIds: ['source-trace-agent', 'letter-shape-agent', 'document-export-shape-agent'], reviewAgentIds: ['evidence-qa-agent', 'wording-risk-agent'], requiredGate: 'שער חוות דעת סטטית', allowedMode: 'static_preview_only', operationalExecution: false, canRun: false, canPersist: false, canCreateMatter: false, canCreateWorkItem: false, canCreateDocumentRef: false },
  { assignmentId: 'assignment-process-capital-gains-v1', processId: 'process-capital-gains', primaryAgentIds: ['capital-gains-context-agent'], supportingAgentIds: ['income-tax-router-agent', 'section-102-pointer-agent', 'source-trace-agent'], reviewAgentIds: ['evidence-qa-agent', 'safety-qa-agent'], requiredGate: 'שער רווח הון סטטי', allowedMode: 'static_preview_only', operationalExecution: false, canRun: false, canPersist: false, canCreateMatter: false, canCreateWorkItem: false, canCreateDocumentRef: false },
  { assignmentId: 'assignment-process-guardian-v1', processId: 'process-guardian', primaryAgentIds: ['case-shape-preview-agent'], supportingAgentIds: ['client-context-agent', 'duplicate-risk-agent', 'filing-package-shape-agent'], reviewAgentIds: ['evidence-qa-agent', 'safety-qa-agent'], requiredGate: 'שער אפוטרופוס סטטי', allowedMode: 'static_preview_only', operationalExecution: false, canRun: false, canPersist: false, canCreateMatter: false, canCreateWorkItem: false, canCreateDocumentRef: false },
  { assignmentId: 'assignment-process-war-compensation-v1', processId: 'process-war-compensation', primaryAgentIds: ['external-source-index-agent'], supportingAgentIds: ['scanned-intake-index-agent', 'document-kind-preview-agent', 'intake-signal-agent', 'missing-fields-agent'], reviewAgentIds: ['evidence-qa-agent', 'safety-qa-agent'], requiredGate: 'שער פיצויי מלחמה סטטי', allowedMode: 'static_preview_only', operationalExecution: false, canRun: false, canPersist: false, canCreateMatter: false, canCreateWorkItem: false, canCreateDocumentRef: false },
  { assignmentId: 'assignment-process-insolvency-v1', processId: 'process-insolvency', primaryAgentIds: ['client-context-agent'], supportingAgentIds: ['case-shape-preview-agent', 'source-trace-agent', 'filing-package-shape-agent', 'document-export-shape-agent'], reviewAgentIds: ['wording-risk-agent', 'safety-qa-agent'], requiredGate: 'שער חדלות פירעון סטטי', allowedMode: 'static_preview_only', operationalExecution: false, canRun: false, canPersist: false, canCreateMatter: false, canCreateWorkItem: false, canCreateDocumentRef: false },
];
// #endregion
