/* ============================================
   FILE: learning-static-seed.ts
   PURPOSE: Static mock seed for Brain Learning System candidates.
   DEPENDENCIES: learning-types
   EXPORTS: LEARNING_STATIC_SEED
   ============================================ */

// #region Imports
import type { LearningCandidate } from './learning-types';
// #endregion

// #region Static Seed
/** Static mock learning seed; no item is binding or approved. */
export const LEARNING_STATIC_SEED = [
  {
    candidateId: 'learning-insight-2026-04-21-vat-ingestion-vs-claiming',
    title: 'VAT Ingestion vs Claiming',
    summary: 'Metadata-only VAT process boundary insight. No full markdown content imported.',
    knowledgeDomains: ['vat', 'bookkeeping'],
    workflows: ['monthly_vat_reconciliation', 'document_ingestion'],
    outputTypes: ['architectural_rule', 'process_boundary'],
    entities: ['universal'],
    sourceChannels: ['eldad_decision_log'],
    status: 'pending_eldad_review',
    hypothesis: 'Metadata-only VAT insight candidate distinguishing ingestion from claiming boundaries.',
    sourceEvidence: [
      {
        evidenceId: 'learning-evidence-insight-2026-04-21-vat-ingestion-vs-claiming',
        sourceKind: 'operator_note',
        sourceLabel: 'Approved VAT insight metadata: VAT Ingestion vs Claiming',
        sourceReference: 'insights/2026-04-21-vat-ingestion-vs-claiming.md',
        capturedAt: '2026-05-03T00:00:00.000Z',
        containsPrivateMaterial: false,
        allowedAccess: 'metadata_only',
        reviewStatus: 'source_present',
      },
    ],
    decisionLog: [],
    approvalBoundary: {
      boundary: 'candidate_only',
      canBindKnowledge: false,
      requiresEldadApproval: true,
      approvedByEldad: false,
    },
    bindingUse: 'none',
    createdAt: '2026-05-03T00:00:00.000Z',
    updatedAt: '2026-05-03T00:00:00.000Z',
    notes: 'Approved static seed batch metadata only; no full insight body imported.',
  },
  {
    candidateId: 'learning-insight-2026-04-28-google-play-vat-treatment',
    title: 'Google Play VAT Treatment',
    summary: 'Metadata-only VAT treatment insight for classification review. No full markdown content imported.',
    knowledgeDomains: ['vat', 'international_tax'],
    workflows: ['invoice_classification', 'expense_recognition'],
    outputTypes: ['tax_treatment_rule'],
    entities: ['universal'],
    sourceChannels: ['eldad_decision_log'],
    status: 'pending_eldad_review',
    hypothesis: 'Metadata-only VAT insight candidate for Google Play tax treatment classification.',
    sourceEvidence: [
      {
        evidenceId: 'learning-evidence-insight-2026-04-28-google-play-vat-treatment',
        sourceKind: 'operator_note',
        sourceLabel: 'Approved VAT insight metadata: Google Play VAT Treatment',
        sourceReference: 'insights/2026-04-28-google-play-vat-treatment.md',
        capturedAt: '2026-05-03T00:00:00.000Z',
        containsPrivateMaterial: false,
        allowedAccess: 'metadata_only',
        reviewStatus: 'source_present',
      },
    ],
    decisionLog: [],
    approvalBoundary: {
      boundary: 'candidate_only',
      canBindKnowledge: false,
      requiresEldadApproval: true,
      approvedByEldad: false,
    },
    bindingUse: 'none',
    createdAt: '2026-05-03T00:00:00.000Z',
    updatedAt: '2026-05-03T00:00:00.000Z',
    notes: 'Approved static seed batch metadata only; no full insight body imported.',
  },
  {
    candidateId: 'learning-seed-vat-review-001',
    title: 'מע"מ review pattern candidate',
    summary: 'Mock metadata summary for VAT review workflow learning.',
    knowledgeDomains: ['מע"מ', 'הנהלת חשבונות'],
    workflows: ['דיווח מע"מ'],
    outputTypes: ['דוח', 'PDF'],
    entities: ['דוד אלדד'],
    sourceChannels: ['סריקה'],
    status: 'needs_source',
    hypothesis: 'VAT workflow signals should remain candidates until source evidence is reviewed.',
    sourceEvidence: [
      {
        evidenceId: 'learning-evidence-vat-review-001',
        sourceKind: 'static_mock_seed',
        sourceLabel: 'Mock VAT process learning signal',
        sourceReference: 'static-seed:vat-process-review',
        capturedAt: '2026-05-03T00:00:00.000Z',
        containsPrivateMaterial: false,
        allowedAccess: 'metadata_only',
        reviewStatus: 'source_required',
      },
    ],
    decisionLog: [],
    approvalBoundary: {
      boundary: 'candidate_only',
      canBindKnowledge: false,
      requiresEldadApproval: true,
      approvedByEldad: false,
    },
    bindingUse: 'none',
    createdAt: '2026-05-03T00:00:00.000Z',
    updatedAt: '2026-05-03T00:00:00.000Z',
    notes: 'Static mock seed only; not approved and not binding.',
  },
  {
    candidateId: 'learning-seed-opinion-workflow-001',
    title: 'חוות דעת workflow corpus candidate',
    summary: 'Mock metadata summary for expert-opinion workflow learning.',
    knowledgeDomains: ['מיסוי'],
    workflows: ['חוות דעת'],
    outputTypes: ['חוות דעת', 'PDF'],
    entities: ['כללי / ללא לקוח'],
    sourceChannels: ['ידני'],
    status: 'pending_eldad_review',
    hypothesis: 'Expert opinion work can become a learning corpus only after Eldad review.',
    sourceEvidence: [
      {
        evidenceId: 'learning-evidence-opinion-workflow-001',
        sourceKind: 'expert_workflow_metadata',
        sourceLabel: 'Mock expert opinion workflow metadata',
        sourceReference: 'static-seed:expert-opinion-workflow',
        capturedAt: '2026-05-03T00:00:00.000Z',
        containsPrivateMaterial: false,
        allowedAccess: 'metadata_only',
        reviewStatus: 'unverified',
      },
    ],
    decisionLog: [],
    approvalBoundary: {
      boundary: 'candidate_only',
      canBindKnowledge: false,
      requiresEldadApproval: true,
      approvedByEldad: false,
    },
    bindingUse: 'reference_only',
    createdAt: '2026-05-03T00:00:00.000Z',
    updatedAt: '2026-05-03T00:00:00.000Z',
    notes: 'Reference-only mock seed; no operational approval.',
  },
  {
    candidateId: 'learning-seed-war-compensation-001',
    title: 'פיצויי מלחמה evidence pattern candidate',
    summary: 'Mock metadata summary for war-compensation evidence patterns.',
    knowledgeDomains: ['פיצויי מלחמה', 'מס הכנסה'],
    workflows: ['מילוי טפסים', 'ביטול קנס'],
    outputTypes: ['חישוב', 'מכתב'],
    entities: ['דימה'],
    sourceChannels: ['סריקה', 'ידני'],
    status: 'draft',
    hypothesis: 'War compensation patterns must stay draft until multi-source evidence is checked.',
    sourceEvidence: [
      {
        evidenceId: 'learning-evidence-war-compensation-001',
        sourceKind: 'professional_pattern',
        sourceLabel: 'Mock war compensation evidence-chain signal',
        sourceReference: 'static-seed:war-compensation-evidence-chain',
        capturedAt: '2026-05-03T00:00:00.000Z',
        containsPrivateMaterial: false,
        allowedAccess: 'metadata_only',
        reviewStatus: 'unverified',
      },
    ],
    decisionLog: [],
    approvalBoundary: {
      boundary: 'candidate_only',
      canBindKnowledge: false,
      requiresEldadApproval: true,
      approvedByEldad: false,
    },
    bindingUse: 'none',
    createdAt: '2026-05-03T00:00:00.000Z',
    updatedAt: '2026-05-03T00:00:00.000Z',
    notes: 'Static mock seed only; no real client facts included.',
  },
] satisfies readonly LearningCandidate[];
// #endregion
