/* ====
   FILE: real-actions-policy-map.ts
   PURPOSE: Static Stage 9 blocked policy map for future real actions.
   DEPENDENCIES: Real-action policy contracts
   EXPORTS: Static real-action policies
   ==== */

// #region Imports
import type { RealActionPolicy } from './real-actions-policy-types';
import { REAL_ACTION_POLICY_STATUS } from './real-actions-policy-types';
// #endregion

// #region Shared Policy Fragments
const defaultRequiredGates = [
  'agent_a_real_action_gate',
  'eldad_explicit_action_approval',
  'stage_9_policy_review',
] as const;

const highRiskRequiredGates = [
  ...defaultRequiredGates,
  'audit_design_gate',
] as const;

const defaultAuditFields = [
  'policyId',
  'actionName',
  'riskLevel',
  'eldadApprovalReference',
] as const;

const defaultForbiddenEffects = [
  'live_provider_call',
  'file_operation',
  'durable_write',
  'operational_record_generation',
  'automatic_submission',
] as const;
// #endregion

// #region Policy Map
/** Static Stage 9 policy map. Every policy is blocked and non-running. */
export const REAL_ACTIONS_POLICY_MAP: readonly RealActionPolicy[] = [
  {
    policyId: 'real-action-policy-classify-intake-candidate',
    actionName: 'classify_intake_candidate',
    riskLevel: 1,
    riskName: 'low',
    status: REAL_ACTION_POLICY_STATUS,
    implementationBlocked: true,
    manualOnly: false,
    requiredGates: defaultRequiredGates,
    requiresAuditLog: false,
    auditMustInclude: defaultAuditFields,
    isReversible: true,
    rollbackMethod: 'undo',
    rollbackRequiresEldad: true,
    forbiddenEffects: defaultForbiddenEffects,
    reason: 'Classification remains policy-only until a later gated implementation.',
  },
  {
    policyId: 'real-action-policy-create-work-item',
    actionName: 'create_work_item',
    riskLevel: 3,
    riskName: 'high',
    status: REAL_ACTION_POLICY_STATUS,
    implementationBlocked: true,
    manualOnly: false,
    requiredGates: highRiskRequiredGates,
    requiresAuditLog: true,
    auditMustInclude: defaultAuditFields,
    isReversible: true,
    rollbackMethod: 'undo',
    rollbackRequiresEldad: true,
    forbiddenEffects: defaultForbiddenEffects,
    reason: 'Work suggestions cannot become real records in Stage 9.',
  },
  {
    policyId: 'real-action-policy-link-to-matter',
    actionName: 'link_to_matter',
    riskLevel: 3,
    riskName: 'high',
    status: REAL_ACTION_POLICY_STATUS,
    implementationBlocked: true,
    manualOnly: false,
    requiredGates: highRiskRequiredGates,
    requiresAuditLog: true,
    auditMustInclude: defaultAuditFields,
    isReversible: true,
    rollbackMethod: 'manual_restore',
    rollbackRequiresEldad: true,
    forbiddenEffects: defaultForbiddenEffects,
    reason: 'Case linkage remains a blocked policy until a later gated implementation.',
  },
  {
    policyId: 'real-action-policy-create-document-ref',
    actionName: 'create_document_ref',
    riskLevel: 3,
    riskName: 'high',
    status: REAL_ACTION_POLICY_STATUS,
    implementationBlocked: true,
    manualOnly: false,
    requiredGates: highRiskRequiredGates,
    requiresAuditLog: true,
    auditMustInclude: defaultAuditFields,
    isReversible: true,
    rollbackMethod: 'manual_restore',
    rollbackRequiresEldad: true,
    forbiddenEffects: defaultForbiddenEffects,
    reason: 'Document reference creation remains blocked in Stage 9.',
  },
  {
    policyId: 'real-action-policy-approve-learning-candidate',
    actionName: 'approve_learning_candidate',
    riskLevel: 2,
    riskName: 'medium',
    status: REAL_ACTION_POLICY_STATUS,
    implementationBlocked: true,
    manualOnly: false,
    requiredGates: defaultRequiredGates,
    requiresAuditLog: false,
    auditMustInclude: defaultAuditFields,
    isReversible: true,
    rollbackMethod: 'undo',
    rollbackRequiresEldad: true,
    forbiddenEffects: defaultForbiddenEffects,
    reason: 'Learning approval stays blocked until a later knowledge gate.',
  },
  {
    policyId: 'real-action-policy-file-document-to-vault',
    actionName: 'file_document_to_vault',
    riskLevel: 3,
    riskName: 'high',
    status: REAL_ACTION_POLICY_STATUS,
    implementationBlocked: true,
    manualOnly: false,
    requiredGates: highRiskRequiredGates,
    requiresAuditLog: true,
    auditMustInclude: defaultAuditFields,
    isReversible: true,
    rollbackMethod: 'manual_restore',
    rollbackRequiresEldad: true,
    forbiddenEffects: defaultForbiddenEffects,
    reason: 'Vault filing remains a blocked policy with no file operation in Stage 9.',
  },
  {
    policyId: 'real-action-policy-move-file',
    actionName: 'move_file',
    riskLevel: 3,
    riskName: 'high',
    status: REAL_ACTION_POLICY_STATUS,
    implementationBlocked: true,
    manualOnly: false,
    requiredGates: highRiskRequiredGates,
    requiresAuditLog: true,
    auditMustInclude: defaultAuditFields,
    isReversible: true,
    rollbackMethod: 'manual_restore',
    rollbackRequiresEldad: true,
    forbiddenEffects: defaultForbiddenEffects,
    reason: 'File movement is blocked and has no file operation in Stage 9.',
  },
  {
    policyId: 'real-action-policy-rename-file',
    actionName: 'rename_file',
    riskLevel: 3,
    riskName: 'high',
    status: REAL_ACTION_POLICY_STATUS,
    implementationBlocked: true,
    manualOnly: false,
    requiredGates: highRiskRequiredGates,
    requiresAuditLog: true,
    auditMustInclude: defaultAuditFields,
    isReversible: true,
    rollbackMethod: 'manual_restore',
    rollbackRequiresEldad: true,
    forbiddenEffects: defaultForbiddenEffects,
    reason: 'File renaming is blocked and has no file operation in Stage 9.',
  },
  {
    policyId: 'real-action-policy-generate-client-letter',
    actionName: 'generate_client_letter',
    riskLevel: 3,
    riskName: 'high',
    status: REAL_ACTION_POLICY_STATUS,
    implementationBlocked: true,
    manualOnly: true,
    requiredGates: highRiskRequiredGates,
    requiresAuditLog: true,
    auditMustInclude: defaultAuditFields,
    isReversible: true,
    rollbackMethod: 'manual_restore',
    rollbackRequiresEldad: true,
    forbiddenEffects: defaultForbiddenEffects,
    reason: 'Client letter generation remains manual-only and blocked in Stage 9.',
  },
  {
    policyId: 'real-action-policy-submit-vat-report',
    actionName: 'submit_vat_report',
    riskLevel: 4,
    riskName: 'critical',
    status: REAL_ACTION_POLICY_STATUS,
    implementationBlocked: true,
    manualOnly: true,
    requiredGates: highRiskRequiredGates,
    requiresAuditLog: true,
    auditMustInclude: defaultAuditFields,
    isReversible: false,
    rollbackMethod: 'not_reversible',
    rollbackRequiresEldad: true,
    forbiddenEffects: defaultForbiddenEffects,
    reason: 'VAT submission is critical, manual-only, and blocked in Stage 9.',
  },
  {
    policyId: 'real-action-policy-submit-tax-filing',
    actionName: 'submit_tax_filing',
    riskLevel: 4,
    riskName: 'critical',
    status: REAL_ACTION_POLICY_STATUS,
    implementationBlocked: true,
    manualOnly: true,
    requiredGates: highRiskRequiredGates,
    requiresAuditLog: true,
    auditMustInclude: defaultAuditFields,
    isReversible: false,
    rollbackMethod: 'not_reversible',
    rollbackRequiresEldad: true,
    forbiddenEffects: defaultForbiddenEffects,
    reason: 'Tax filing submission is critical, manual-only, and blocked in Stage 9.',
  },
  {
    policyId: 'real-action-policy-send-email-reply',
    actionName: 'send_email_reply',
    riskLevel: 4,
    riskName: 'critical',
    status: REAL_ACTION_POLICY_STATUS,
    implementationBlocked: true,
    manualOnly: true,
    requiredGates: highRiskRequiredGates,
    requiresAuditLog: true,
    auditMustInclude: defaultAuditFields,
    isReversible: false,
    rollbackMethod: 'not_reversible',
    rollbackRequiresEldad: true,
    forbiddenEffects: defaultForbiddenEffects,
    reason: 'Email replies are critical, manual-only, and blocked in Stage 9.',
  },
  {
    policyId: 'real-action-policy-delete-file',
    actionName: 'delete_file',
    riskLevel: 4,
    riskName: 'critical',
    status: REAL_ACTION_POLICY_STATUS,
    implementationBlocked: true,
    manualOnly: true,
    requiredGates: highRiskRequiredGates,
    requiresAuditLog: true,
    auditMustInclude: defaultAuditFields,
    isReversible: false,
    rollbackMethod: 'not_reversible',
    rollbackRequiresEldad: true,
    forbiddenEffects: defaultForbiddenEffects,
    reason: 'File deletion is critical, manual-only, and blocked in Stage 9.',
  },
] as const;
// #endregion
