import {
  VAT_STATIC_EVIDENCE_MISSING,
  VAT_STATIC_EVIDENCE_SOURCE_ARTIFACT,
  type VatStaticEvidenceRecord,
} from './vat-static-evidence-types';

const CLIENT_OR_MATTER = 'דוד אלדד - מע"מ 1-2.26';

const recordedReviewNote =
  'נרשם לפי דוח תנועות יומן סטטי שכבר חולץ. אין גישה חיה למערכת הנהלת החשבונות, ואין שדה סך כולל מאומת.';

const vatReportAssignmentFor = (reportMonth: string) =>
  `חודש דיווח ${reportMonth} לפי דוח תנועות היומן; דורש בדיקת אלדד לפני שימוש תפעולי`;

/** First static VAT evidence seed from already extracted bookkeeping journal rows. */
export const STATIC_VAT_EVIDENCE_RECORDS: readonly VatStaticEvidenceRecord[] = [
  {
    evidenceId: 'vat-static-evidence-2026-01-electric-company',
    clientOrMatter: CLIENT_OR_MATTER,
    supplier: 'חברת החשמל',
    invoiceDate: '09/01/2026',
    periodDescription: '10/11/25 ועד 08/01/2026',
    reportMonth: '01/2026',
    amountFieldAsInSource: '468.93',
    vatAmount: '71.53',
    totalIfKnown: VAT_STATIC_EVIDENCE_MISSING,
    accountingSystemStatus: 'recorded_in_accounting_system',
    accountingReference: VAT_STATIC_EVIDENCE_MISSING,
    vatReportAssignment: vatReportAssignmentFor('01/2026'),
    expenseClassification: 'הוצאה מעורבת - דורש בדיקת אלדד',
    sourceArtifact: VAT_STATIC_EVIDENCE_SOURCE_ARTIFACT,
    confidence: 'high',
    reviewNote: recordedReviewNote,
  },
  {
    evidenceId: 'vat-static-evidence-2026-01-cellcom',
    clientOrMatter: CLIENT_OR_MATTER,
    supplier: 'סלקום',
    invoiceDate: '02/01/2026',
    periodDescription: '02.12.25-01.01.26',
    reportMonth: '01/2026',
    amountFieldAsInSource: '115.98',
    vatAmount: '11.79',
    totalIfKnown: VAT_STATIC_EVIDENCE_MISSING,
    accountingSystemStatus: 'recorded_in_accounting_system',
    accountingReference: '368265962',
    vatReportAssignment: vatReportAssignmentFor('01/2026'),
    expenseClassification: 'תקשורת - דורש בדיקת אלדד',
    sourceArtifact: VAT_STATIC_EVIDENCE_SOURCE_ARTIFACT,
    confidence: 'high',
    reviewNote: recordedReviewNote,
  },
  {
    evidenceId: 'vat-static-evidence-2026-01-bezeq',
    clientOrMatter: CLIENT_OR_MATTER,
    supplier: 'בזק',
    invoiceDate: '06/01/2026',
    periodDescription: 'דצמבר 2025',
    reportMonth: '01/2026',
    amountFieldAsInSource: '365.74',
    vatAmount: '55.79',
    totalIfKnown: VAT_STATIC_EVIDENCE_MISSING,
    accountingSystemStatus: 'recorded_in_accounting_system',
    accountingReference: '240095900',
    vatReportAssignment: vatReportAssignmentFor('01/2026'),
    expenseClassification: 'תקשורת - דורש בדיקת אלדד',
    sourceArtifact: VAT_STATIC_EVIDENCE_SOURCE_ARTIFACT,
    confidence: 'high',
    reviewNote: recordedReviewNote,
  },
  {
    evidenceId: 'vat-static-evidence-2026-01-oketz',
    clientOrMatter: CLIENT_OR_MATTER,
    supplier: 'עוקץ',
    invoiceDate: '08/01/2026',
    periodDescription: 'מנוי שנתי עוקץ טריו',
    reportMonth: '01/2026',
    amountFieldAsInSource: '2,850.00',
    vatAmount: '434.75',
    totalIfKnown: VAT_STATIC_EVIDENCE_MISSING,
    accountingSystemStatus: 'recorded_in_accounting_system',
    accountingReference: '5006273',
    vatReportAssignment: vatReportAssignmentFor('01/2026'),
    expenseClassification: 'תוכנות ושירותים - דורש בדיקת אלדד',
    sourceArtifact: VAT_STATIC_EVIDENCE_SOURCE_ARTIFACT,
    confidence: 'high',
    reviewNote: recordedReviewNote,
  },
  {
    evidenceId: 'vat-static-evidence-2026-01-maven-solutions',
    clientOrMatter: CLIENT_OR_MATTER,
    supplier: 'מייבן פתרונות',
    invoiceDate: '01/01/2026',
    periodDescription: 'דמי מנוי 1/26',
    reportMonth: '01/2026',
    amountFieldAsInSource: '236.00',
    vatAmount: '36.00',
    totalIfKnown: VAT_STATIC_EVIDENCE_MISSING,
    accountingSystemStatus: 'recorded_in_accounting_system',
    accountingReference: VAT_STATIC_EVIDENCE_MISSING,
    vatReportAssignment: vatReportAssignmentFor('01/2026'),
    expenseClassification: 'תוכנות ושירותים - דורש בדיקת אלדד',
    sourceArtifact: VAT_STATIC_EVIDENCE_SOURCE_ARTIFACT,
    confidence: 'high',
    reviewNote: recordedReviewNote,
  },
  {
    evidenceId: 'vat-static-evidence-2026-02-maven-solutions',
    clientOrMatter: CLIENT_OR_MATTER,
    supplier: 'מייבן פתרונות',
    invoiceDate: '01/02/2026',
    periodDescription: 'דמי מנוי 2/26',
    reportMonth: '02/2026',
    amountFieldAsInSource: '236.00',
    vatAmount: '36.00',
    totalIfKnown: VAT_STATIC_EVIDENCE_MISSING,
    accountingSystemStatus: 'recorded_in_accounting_system',
    accountingReference: VAT_STATIC_EVIDENCE_MISSING,
    vatReportAssignment: vatReportAssignmentFor('02/2026'),
    expenseClassification: 'תוכנות ושירותים - דורש בדיקת אלדד',
    sourceArtifact: VAT_STATIC_EVIDENCE_SOURCE_ARTIFACT,
    confidence: 'high',
    reviewNote: recordedReviewNote,
  },
  {
    evidenceId: 'vat-static-evidence-2026-02-bezeq',
    clientOrMatter: CLIENT_OR_MATTER,
    supplier: 'בזק',
    invoiceDate: '06/02/2026',
    periodDescription: 'ינואר 2026',
    reportMonth: '02/2026',
    amountFieldAsInSource: '390.45',
    vatAmount: '59.56',
    totalIfKnown: VAT_STATIC_EVIDENCE_MISSING,
    accountingSystemStatus: 'recorded_in_accounting_system',
    accountingReference: VAT_STATIC_EVIDENCE_MISSING,
    vatReportAssignment: vatReportAssignmentFor('02/2026'),
    expenseClassification: 'תקשורת - דורש בדיקת אלדד',
    sourceArtifact: VAT_STATIC_EVIDENCE_SOURCE_ARTIFACT,
    confidence: 'high',
    reviewNote: recordedReviewNote,
  },
  {
    evidenceId: 'vat-static-evidence-2026-02-oketz',
    clientOrMatter: CLIENT_OR_MATTER,
    supplier: 'עוקץ',
    invoiceDate: '15/02/2026',
    periodDescription: 'מנוי שנתי עוקץ טריו / תוספת',
    reportMonth: '02/2026',
    amountFieldAsInSource: '1,376.00',
    vatAmount: '209.90',
    totalIfKnown: VAT_STATIC_EVIDENCE_MISSING,
    accountingSystemStatus: 'recorded_in_accounting_system',
    accountingReference: '5006586',
    vatReportAssignment: vatReportAssignmentFor('02/2026'),
    expenseClassification: 'תוכנות ושירותים - דורש בדיקת אלדד',
    sourceArtifact: VAT_STATIC_EVIDENCE_SOURCE_ARTIFACT,
    confidence: 'high',
    reviewNote: recordedReviewNote,
  },
];
